// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_town.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_client_5ftown_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_client_5ftown_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
#include "game_types.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_client_5ftown_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_client_5ftown_2eproto {
  static const uint32_t offsets[];
};
namespace PB {
namespace Town {
class ScenePlayerEnterPush;
struct ScenePlayerEnterPushDefaultTypeInternal;
extern ScenePlayerEnterPushDefaultTypeInternal _ScenePlayerEnterPush_default_instance_;
class ScenePlayerLeavePush;
struct ScenePlayerLeavePushDefaultTypeInternal;
extern ScenePlayerLeavePushDefaultTypeInternal _ScenePlayerLeavePush_default_instance_;
class ScenePlayerStatePush;
struct ScenePlayerStatePushDefaultTypeInternal;
extern ScenePlayerStatePushDefaultTypeInternal _ScenePlayerStatePush_default_instance_;
class TownPlayerStatePush;
struct TownPlayerStatePushDefaultTypeInternal;
extern TownPlayerStatePushDefaultTypeInternal _TownPlayerStatePush_default_instance_;
}  // namespace Town
}  // namespace PB
PROTOBUF_NAMESPACE_OPEN
template<> ::PB::Town::ScenePlayerEnterPush* Arena::CreateMaybeMessage<::PB::Town::ScenePlayerEnterPush>(Arena*);
template<> ::PB::Town::ScenePlayerLeavePush* Arena::CreateMaybeMessage<::PB::Town::ScenePlayerLeavePush>(Arena*);
template<> ::PB::Town::ScenePlayerStatePush* Arena::CreateMaybeMessage<::PB::Town::ScenePlayerStatePush>(Arena*);
template<> ::PB::Town::TownPlayerStatePush* Arena::CreateMaybeMessage<::PB::Town::TownPlayerStatePush>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PB {
namespace Town {

enum TownPlayerStatePush_MsgId : int {
  TownPlayerStatePush_MsgId_None = 0,
  TownPlayerStatePush_MsgId_Id = 30000,
  TownPlayerStatePush_MsgId_TownPlayerStatePush_MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  TownPlayerStatePush_MsgId_TownPlayerStatePush_MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool TownPlayerStatePush_MsgId_IsValid(int value);
constexpr TownPlayerStatePush_MsgId TownPlayerStatePush_MsgId_MsgId_MIN = TownPlayerStatePush_MsgId_None;
constexpr TownPlayerStatePush_MsgId TownPlayerStatePush_MsgId_MsgId_MAX = TownPlayerStatePush_MsgId_Id;
constexpr int TownPlayerStatePush_MsgId_MsgId_ARRAYSIZE = TownPlayerStatePush_MsgId_MsgId_MAX + 1;

const std::string& TownPlayerStatePush_MsgId_Name(TownPlayerStatePush_MsgId value);
template<typename T>
inline const std::string& TownPlayerStatePush_MsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TownPlayerStatePush_MsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TownPlayerStatePush_MsgId_Name.");
  return TownPlayerStatePush_MsgId_Name(static_cast<TownPlayerStatePush_MsgId>(enum_t_value));
}
bool TownPlayerStatePush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TownPlayerStatePush_MsgId* value);
enum ScenePlayerEnterPush_MsgId : int {
  ScenePlayerEnterPush_MsgId_None = 0,
  ScenePlayerEnterPush_MsgId_Id = 30001,
  ScenePlayerEnterPush_MsgId_ScenePlayerEnterPush_MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ScenePlayerEnterPush_MsgId_ScenePlayerEnterPush_MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ScenePlayerEnterPush_MsgId_IsValid(int value);
constexpr ScenePlayerEnterPush_MsgId ScenePlayerEnterPush_MsgId_MsgId_MIN = ScenePlayerEnterPush_MsgId_None;
constexpr ScenePlayerEnterPush_MsgId ScenePlayerEnterPush_MsgId_MsgId_MAX = ScenePlayerEnterPush_MsgId_Id;
constexpr int ScenePlayerEnterPush_MsgId_MsgId_ARRAYSIZE = ScenePlayerEnterPush_MsgId_MsgId_MAX + 1;

const std::string& ScenePlayerEnterPush_MsgId_Name(ScenePlayerEnterPush_MsgId value);
template<typename T>
inline const std::string& ScenePlayerEnterPush_MsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ScenePlayerEnterPush_MsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ScenePlayerEnterPush_MsgId_Name.");
  return ScenePlayerEnterPush_MsgId_Name(static_cast<ScenePlayerEnterPush_MsgId>(enum_t_value));
}
bool ScenePlayerEnterPush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ScenePlayerEnterPush_MsgId* value);
enum ScenePlayerLeavePush_MsgId : int {
  ScenePlayerLeavePush_MsgId_None = 0,
  ScenePlayerLeavePush_MsgId_Id = 30002,
  ScenePlayerLeavePush_MsgId_ScenePlayerLeavePush_MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ScenePlayerLeavePush_MsgId_ScenePlayerLeavePush_MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ScenePlayerLeavePush_MsgId_IsValid(int value);
constexpr ScenePlayerLeavePush_MsgId ScenePlayerLeavePush_MsgId_MsgId_MIN = ScenePlayerLeavePush_MsgId_None;
constexpr ScenePlayerLeavePush_MsgId ScenePlayerLeavePush_MsgId_MsgId_MAX = ScenePlayerLeavePush_MsgId_Id;
constexpr int ScenePlayerLeavePush_MsgId_MsgId_ARRAYSIZE = ScenePlayerLeavePush_MsgId_MsgId_MAX + 1;

const std::string& ScenePlayerLeavePush_MsgId_Name(ScenePlayerLeavePush_MsgId value);
template<typename T>
inline const std::string& ScenePlayerLeavePush_MsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ScenePlayerLeavePush_MsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ScenePlayerLeavePush_MsgId_Name.");
  return ScenePlayerLeavePush_MsgId_Name(static_cast<ScenePlayerLeavePush_MsgId>(enum_t_value));
}
bool ScenePlayerLeavePush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ScenePlayerLeavePush_MsgId* value);
enum ScenePlayerStatePush_MsgId : int {
  ScenePlayerStatePush_MsgId_None = 0,
  ScenePlayerStatePush_MsgId_Id = 30003,
  ScenePlayerStatePush_MsgId_ScenePlayerStatePush_MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ScenePlayerStatePush_MsgId_ScenePlayerStatePush_MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ScenePlayerStatePush_MsgId_IsValid(int value);
constexpr ScenePlayerStatePush_MsgId ScenePlayerStatePush_MsgId_MsgId_MIN = ScenePlayerStatePush_MsgId_None;
constexpr ScenePlayerStatePush_MsgId ScenePlayerStatePush_MsgId_MsgId_MAX = ScenePlayerStatePush_MsgId_Id;
constexpr int ScenePlayerStatePush_MsgId_MsgId_ARRAYSIZE = ScenePlayerStatePush_MsgId_MsgId_MAX + 1;

const std::string& ScenePlayerStatePush_MsgId_Name(ScenePlayerStatePush_MsgId value);
template<typename T>
inline const std::string& ScenePlayerStatePush_MsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ScenePlayerStatePush_MsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ScenePlayerStatePush_MsgId_Name.");
  return ScenePlayerStatePush_MsgId_Name(static_cast<ScenePlayerStatePush_MsgId>(enum_t_value));
}
bool ScenePlayerStatePush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ScenePlayerStatePush_MsgId* value);
// ===================================================================

class TownPlayerStatePush final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Town.TownPlayerStatePush) */ {
 public:
  inline TownPlayerStatePush() : TownPlayerStatePush(nullptr) {}
  ~TownPlayerStatePush() override;
  explicit PROTOBUF_CONSTEXPR TownPlayerStatePush(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TownPlayerStatePush(const TownPlayerStatePush& from);
  TownPlayerStatePush(TownPlayerStatePush&& from) noexcept
    : TownPlayerStatePush() {
    *this = ::std::move(from);
  }

  inline TownPlayerStatePush& operator=(const TownPlayerStatePush& from) {
    CopyFrom(from);
    return *this;
  }
  inline TownPlayerStatePush& operator=(TownPlayerStatePush&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const TownPlayerStatePush& default_instance() {
    return *internal_default_instance();
  }
  static inline const TownPlayerStatePush* internal_default_instance() {
    return reinterpret_cast<const TownPlayerStatePush*>(
               &_TownPlayerStatePush_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TownPlayerStatePush& a, TownPlayerStatePush& b) {
    a.Swap(&b);
  }
  inline void Swap(TownPlayerStatePush* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TownPlayerStatePush* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TownPlayerStatePush* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TownPlayerStatePush>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const TownPlayerStatePush& from);
  void MergeFrom(const TownPlayerStatePush& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TownPlayerStatePush* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Town.TownPlayerStatePush";
  }
  protected:
  explicit TownPlayerStatePush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef TownPlayerStatePush_MsgId MsgId;
  static constexpr MsgId None =
    TownPlayerStatePush_MsgId_None;
  static constexpr MsgId Id =
    TownPlayerStatePush_MsgId_Id;
  static inline bool MsgId_IsValid(int value) {
    return TownPlayerStatePush_MsgId_IsValid(value);
  }
  static constexpr MsgId MsgId_MIN =
    TownPlayerStatePush_MsgId_MsgId_MIN;
  static constexpr MsgId MsgId_MAX =
    TownPlayerStatePush_MsgId_MsgId_MAX;
  static constexpr int MsgId_ARRAYSIZE =
    TownPlayerStatePush_MsgId_MsgId_ARRAYSIZE;
  template<typename T>
  static inline const std::string& MsgId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgId_Name.");
    return TownPlayerStatePush_MsgId_Name(enum_t_value);
  }
  static inline bool MsgId_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MsgId* value) {
    return TownPlayerStatePush_MsgId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 1,
  };
  // .PB.Types.PlayerState state = 1;
  bool has_state() const;
  private:
  bool _internal_has_state() const;
  public:
  void clear_state();
  const ::PB::Types::PlayerState& state() const;
  PROTOBUF_NODISCARD ::PB::Types::PlayerState* release_state();
  ::PB::Types::PlayerState* mutable_state();
  void set_allocated_state(::PB::Types::PlayerState* state);
  private:
  const ::PB::Types::PlayerState& _internal_state() const;
  ::PB::Types::PlayerState* _internal_mutable_state();
  public:
  void unsafe_arena_set_allocated_state(
      ::PB::Types::PlayerState* state);
  ::PB::Types::PlayerState* unsafe_arena_release_state();

  // @@protoc_insertion_point(class_scope:PB.Town.TownPlayerStatePush)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PB::Types::PlayerState* state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5ftown_2eproto;
};
// -------------------------------------------------------------------

class ScenePlayerEnterPush final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Town.ScenePlayerEnterPush) */ {
 public:
  inline ScenePlayerEnterPush() : ScenePlayerEnterPush(nullptr) {}
  ~ScenePlayerEnterPush() override;
  explicit PROTOBUF_CONSTEXPR ScenePlayerEnterPush(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ScenePlayerEnterPush(const ScenePlayerEnterPush& from);
  ScenePlayerEnterPush(ScenePlayerEnterPush&& from) noexcept
    : ScenePlayerEnterPush() {
    *this = ::std::move(from);
  }

  inline ScenePlayerEnterPush& operator=(const ScenePlayerEnterPush& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScenePlayerEnterPush& operator=(ScenePlayerEnterPush&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ScenePlayerEnterPush& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScenePlayerEnterPush* internal_default_instance() {
    return reinterpret_cast<const ScenePlayerEnterPush*>(
               &_ScenePlayerEnterPush_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ScenePlayerEnterPush& a, ScenePlayerEnterPush& b) {
    a.Swap(&b);
  }
  inline void Swap(ScenePlayerEnterPush* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScenePlayerEnterPush* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScenePlayerEnterPush* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ScenePlayerEnterPush>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ScenePlayerEnterPush& from);
  void MergeFrom(const ScenePlayerEnterPush& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ScenePlayerEnterPush* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Town.ScenePlayerEnterPush";
  }
  protected:
  explicit ScenePlayerEnterPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef ScenePlayerEnterPush_MsgId MsgId;
  static constexpr MsgId None =
    ScenePlayerEnterPush_MsgId_None;
  static constexpr MsgId Id =
    ScenePlayerEnterPush_MsgId_Id;
  static inline bool MsgId_IsValid(int value) {
    return ScenePlayerEnterPush_MsgId_IsValid(value);
  }
  static constexpr MsgId MsgId_MIN =
    ScenePlayerEnterPush_MsgId_MsgId_MIN;
  static constexpr MsgId MsgId_MAX =
    ScenePlayerEnterPush_MsgId_MsgId_MAX;
  static constexpr int MsgId_ARRAYSIZE =
    ScenePlayerEnterPush_MsgId_MsgId_ARRAYSIZE;
  template<typename T>
  static inline const std::string& MsgId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgId_Name.");
    return ScenePlayerEnterPush_MsgId_Name(enum_t_value);
  }
  static inline bool MsgId_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MsgId* value) {
    return ScenePlayerEnterPush_MsgId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 1,
  };
  // .PB.Types.PlayerState state = 1;
  bool has_state() const;
  private:
  bool _internal_has_state() const;
  public:
  void clear_state();
  const ::PB::Types::PlayerState& state() const;
  PROTOBUF_NODISCARD ::PB::Types::PlayerState* release_state();
  ::PB::Types::PlayerState* mutable_state();
  void set_allocated_state(::PB::Types::PlayerState* state);
  private:
  const ::PB::Types::PlayerState& _internal_state() const;
  ::PB::Types::PlayerState* _internal_mutable_state();
  public:
  void unsafe_arena_set_allocated_state(
      ::PB::Types::PlayerState* state);
  ::PB::Types::PlayerState* unsafe_arena_release_state();

  // @@protoc_insertion_point(class_scope:PB.Town.ScenePlayerEnterPush)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PB::Types::PlayerState* state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5ftown_2eproto;
};
// -------------------------------------------------------------------

class ScenePlayerLeavePush final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Town.ScenePlayerLeavePush) */ {
 public:
  inline ScenePlayerLeavePush() : ScenePlayerLeavePush(nullptr) {}
  ~ScenePlayerLeavePush() override;
  explicit PROTOBUF_CONSTEXPR ScenePlayerLeavePush(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ScenePlayerLeavePush(const ScenePlayerLeavePush& from);
  ScenePlayerLeavePush(ScenePlayerLeavePush&& from) noexcept
    : ScenePlayerLeavePush() {
    *this = ::std::move(from);
  }

  inline ScenePlayerLeavePush& operator=(const ScenePlayerLeavePush& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScenePlayerLeavePush& operator=(ScenePlayerLeavePush&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ScenePlayerLeavePush& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScenePlayerLeavePush* internal_default_instance() {
    return reinterpret_cast<const ScenePlayerLeavePush*>(
               &_ScenePlayerLeavePush_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ScenePlayerLeavePush& a, ScenePlayerLeavePush& b) {
    a.Swap(&b);
  }
  inline void Swap(ScenePlayerLeavePush* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScenePlayerLeavePush* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScenePlayerLeavePush* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ScenePlayerLeavePush>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ScenePlayerLeavePush& from);
  void MergeFrom(const ScenePlayerLeavePush& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ScenePlayerLeavePush* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Town.ScenePlayerLeavePush";
  }
  protected:
  explicit ScenePlayerLeavePush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef ScenePlayerLeavePush_MsgId MsgId;
  static constexpr MsgId None =
    ScenePlayerLeavePush_MsgId_None;
  static constexpr MsgId Id =
    ScenePlayerLeavePush_MsgId_Id;
  static inline bool MsgId_IsValid(int value) {
    return ScenePlayerLeavePush_MsgId_IsValid(value);
  }
  static constexpr MsgId MsgId_MIN =
    ScenePlayerLeavePush_MsgId_MsgId_MIN;
  static constexpr MsgId MsgId_MAX =
    ScenePlayerLeavePush_MsgId_MsgId_MAX;
  static constexpr int MsgId_ARRAYSIZE =
    ScenePlayerLeavePush_MsgId_MsgId_ARRAYSIZE;
  template<typename T>
  static inline const std::string& MsgId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgId_Name.");
    return ScenePlayerLeavePush_MsgId_Name(enum_t_value);
  }
  static inline bool MsgId_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MsgId* value) {
    return ScenePlayerLeavePush_MsgId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
  };
  // int64 player_id = 1;
  void clear_player_id();
  int64_t player_id() const;
  void set_player_id(int64_t value);
  private:
  int64_t _internal_player_id() const;
  void _internal_set_player_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Town.ScenePlayerLeavePush)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t player_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5ftown_2eproto;
};
// -------------------------------------------------------------------

class ScenePlayerStatePush final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Town.ScenePlayerStatePush) */ {
 public:
  inline ScenePlayerStatePush() : ScenePlayerStatePush(nullptr) {}
  ~ScenePlayerStatePush() override;
  explicit PROTOBUF_CONSTEXPR ScenePlayerStatePush(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ScenePlayerStatePush(const ScenePlayerStatePush& from);
  ScenePlayerStatePush(ScenePlayerStatePush&& from) noexcept
    : ScenePlayerStatePush() {
    *this = ::std::move(from);
  }

  inline ScenePlayerStatePush& operator=(const ScenePlayerStatePush& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScenePlayerStatePush& operator=(ScenePlayerStatePush&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ScenePlayerStatePush& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScenePlayerStatePush* internal_default_instance() {
    return reinterpret_cast<const ScenePlayerStatePush*>(
               &_ScenePlayerStatePush_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ScenePlayerStatePush& a, ScenePlayerStatePush& b) {
    a.Swap(&b);
  }
  inline void Swap(ScenePlayerStatePush* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScenePlayerStatePush* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScenePlayerStatePush* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ScenePlayerStatePush>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ScenePlayerStatePush& from);
  void MergeFrom(const ScenePlayerStatePush& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ScenePlayerStatePush* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Town.ScenePlayerStatePush";
  }
  protected:
  explicit ScenePlayerStatePush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef ScenePlayerStatePush_MsgId MsgId;
  static constexpr MsgId None =
    ScenePlayerStatePush_MsgId_None;
  static constexpr MsgId Id =
    ScenePlayerStatePush_MsgId_Id;
  static inline bool MsgId_IsValid(int value) {
    return ScenePlayerStatePush_MsgId_IsValid(value);
  }
  static constexpr MsgId MsgId_MIN =
    ScenePlayerStatePush_MsgId_MsgId_MIN;
  static constexpr MsgId MsgId_MAX =
    ScenePlayerStatePush_MsgId_MsgId_MAX;
  static constexpr int MsgId_ARRAYSIZE =
    ScenePlayerStatePush_MsgId_MsgId_ARRAYSIZE;
  template<typename T>
  static inline const std::string& MsgId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgId_Name.");
    return ScenePlayerStatePush_MsgId_Name(enum_t_value);
  }
  static inline bool MsgId_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MsgId* value) {
    return ScenePlayerStatePush_MsgId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 1,
  };
  // .PB.Types.PlayerState state = 1;
  bool has_state() const;
  private:
  bool _internal_has_state() const;
  public:
  void clear_state();
  const ::PB::Types::PlayerState& state() const;
  PROTOBUF_NODISCARD ::PB::Types::PlayerState* release_state();
  ::PB::Types::PlayerState* mutable_state();
  void set_allocated_state(::PB::Types::PlayerState* state);
  private:
  const ::PB::Types::PlayerState& _internal_state() const;
  ::PB::Types::PlayerState* _internal_mutable_state();
  public:
  void unsafe_arena_set_allocated_state(
      ::PB::Types::PlayerState* state);
  ::PB::Types::PlayerState* unsafe_arena_release_state();

  // @@protoc_insertion_point(class_scope:PB.Town.ScenePlayerStatePush)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PB::Types::PlayerState* state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5ftown_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TownPlayerStatePush

// .PB.Types.PlayerState state = 1;
inline bool TownPlayerStatePush::_internal_has_state() const {
  return this != internal_default_instance() && _impl_.state_ != nullptr;
}
inline bool TownPlayerStatePush::has_state() const {
  return _internal_has_state();
}
inline const ::PB::Types::PlayerState& TownPlayerStatePush::_internal_state() const {
  const ::PB::Types::PlayerState* p = _impl_.state_;
  return p != nullptr ? *p : reinterpret_cast<const ::PB::Types::PlayerState&>(
      ::PB::Types::_PlayerState_default_instance_);
}
inline const ::PB::Types::PlayerState& TownPlayerStatePush::state() const {
  // @@protoc_insertion_point(field_get:PB.Town.TownPlayerStatePush.state)
  return _internal_state();
}
inline void TownPlayerStatePush::unsafe_arena_set_allocated_state(
    ::PB::Types::PlayerState* state) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.state_);
  }
  _impl_.state_ = state;
  if (state) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PB.Town.TownPlayerStatePush.state)
}
inline ::PB::Types::PlayerState* TownPlayerStatePush::release_state() {
  
  ::PB::Types::PlayerState* temp = _impl_.state_;
  _impl_.state_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PB::Types::PlayerState* TownPlayerStatePush::unsafe_arena_release_state() {
  // @@protoc_insertion_point(field_release:PB.Town.TownPlayerStatePush.state)
  
  ::PB::Types::PlayerState* temp = _impl_.state_;
  _impl_.state_ = nullptr;
  return temp;
}
inline ::PB::Types::PlayerState* TownPlayerStatePush::_internal_mutable_state() {
  
  if (_impl_.state_ == nullptr) {
    auto* p = CreateMaybeMessage<::PB::Types::PlayerState>(GetArenaForAllocation());
    _impl_.state_ = p;
  }
  return _impl_.state_;
}
inline ::PB::Types::PlayerState* TownPlayerStatePush::mutable_state() {
  ::PB::Types::PlayerState* _msg = _internal_mutable_state();
  // @@protoc_insertion_point(field_mutable:PB.Town.TownPlayerStatePush.state)
  return _msg;
}
inline void TownPlayerStatePush::set_allocated_state(::PB::Types::PlayerState* state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.state_);
  }
  if (state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(state));
    if (message_arena != submessage_arena) {
      state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, state, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.state_ = state;
  // @@protoc_insertion_point(field_set_allocated:PB.Town.TownPlayerStatePush.state)
}

// -------------------------------------------------------------------

// ScenePlayerEnterPush

// .PB.Types.PlayerState state = 1;
inline bool ScenePlayerEnterPush::_internal_has_state() const {
  return this != internal_default_instance() && _impl_.state_ != nullptr;
}
inline bool ScenePlayerEnterPush::has_state() const {
  return _internal_has_state();
}
inline const ::PB::Types::PlayerState& ScenePlayerEnterPush::_internal_state() const {
  const ::PB::Types::PlayerState* p = _impl_.state_;
  return p != nullptr ? *p : reinterpret_cast<const ::PB::Types::PlayerState&>(
      ::PB::Types::_PlayerState_default_instance_);
}
inline const ::PB::Types::PlayerState& ScenePlayerEnterPush::state() const {
  // @@protoc_insertion_point(field_get:PB.Town.ScenePlayerEnterPush.state)
  return _internal_state();
}
inline void ScenePlayerEnterPush::unsafe_arena_set_allocated_state(
    ::PB::Types::PlayerState* state) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.state_);
  }
  _impl_.state_ = state;
  if (state) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PB.Town.ScenePlayerEnterPush.state)
}
inline ::PB::Types::PlayerState* ScenePlayerEnterPush::release_state() {
  
  ::PB::Types::PlayerState* temp = _impl_.state_;
  _impl_.state_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PB::Types::PlayerState* ScenePlayerEnterPush::unsafe_arena_release_state() {
  // @@protoc_insertion_point(field_release:PB.Town.ScenePlayerEnterPush.state)
  
  ::PB::Types::PlayerState* temp = _impl_.state_;
  _impl_.state_ = nullptr;
  return temp;
}
inline ::PB::Types::PlayerState* ScenePlayerEnterPush::_internal_mutable_state() {
  
  if (_impl_.state_ == nullptr) {
    auto* p = CreateMaybeMessage<::PB::Types::PlayerState>(GetArenaForAllocation());
    _impl_.state_ = p;
  }
  return _impl_.state_;
}
inline ::PB::Types::PlayerState* ScenePlayerEnterPush::mutable_state() {
  ::PB::Types::PlayerState* _msg = _internal_mutable_state();
  // @@protoc_insertion_point(field_mutable:PB.Town.ScenePlayerEnterPush.state)
  return _msg;
}
inline void ScenePlayerEnterPush::set_allocated_state(::PB::Types::PlayerState* state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.state_);
  }
  if (state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(state));
    if (message_arena != submessage_arena) {
      state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, state, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.state_ = state;
  // @@protoc_insertion_point(field_set_allocated:PB.Town.ScenePlayerEnterPush.state)
}

// -------------------------------------------------------------------

// ScenePlayerLeavePush

// int64 player_id = 1;
inline void ScenePlayerLeavePush::clear_player_id() {
  _impl_.player_id_ = int64_t{0};
}
inline int64_t ScenePlayerLeavePush::_internal_player_id() const {
  return _impl_.player_id_;
}
inline int64_t ScenePlayerLeavePush::player_id() const {
  // @@protoc_insertion_point(field_get:PB.Town.ScenePlayerLeavePush.player_id)
  return _internal_player_id();
}
inline void ScenePlayerLeavePush::_internal_set_player_id(int64_t value) {
  
  _impl_.player_id_ = value;
}
inline void ScenePlayerLeavePush::set_player_id(int64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:PB.Town.ScenePlayerLeavePush.player_id)
}

// -------------------------------------------------------------------

// ScenePlayerStatePush

// .PB.Types.PlayerState state = 1;
inline bool ScenePlayerStatePush::_internal_has_state() const {
  return this != internal_default_instance() && _impl_.state_ != nullptr;
}
inline bool ScenePlayerStatePush::has_state() const {
  return _internal_has_state();
}
inline const ::PB::Types::PlayerState& ScenePlayerStatePush::_internal_state() const {
  const ::PB::Types::PlayerState* p = _impl_.state_;
  return p != nullptr ? *p : reinterpret_cast<const ::PB::Types::PlayerState&>(
      ::PB::Types::_PlayerState_default_instance_);
}
inline const ::PB::Types::PlayerState& ScenePlayerStatePush::state() const {
  // @@protoc_insertion_point(field_get:PB.Town.ScenePlayerStatePush.state)
  return _internal_state();
}
inline void ScenePlayerStatePush::unsafe_arena_set_allocated_state(
    ::PB::Types::PlayerState* state) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.state_);
  }
  _impl_.state_ = state;
  if (state) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PB.Town.ScenePlayerStatePush.state)
}
inline ::PB::Types::PlayerState* ScenePlayerStatePush::release_state() {
  
  ::PB::Types::PlayerState* temp = _impl_.state_;
  _impl_.state_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PB::Types::PlayerState* ScenePlayerStatePush::unsafe_arena_release_state() {
  // @@protoc_insertion_point(field_release:PB.Town.ScenePlayerStatePush.state)
  
  ::PB::Types::PlayerState* temp = _impl_.state_;
  _impl_.state_ = nullptr;
  return temp;
}
inline ::PB::Types::PlayerState* ScenePlayerStatePush::_internal_mutable_state() {
  
  if (_impl_.state_ == nullptr) {
    auto* p = CreateMaybeMessage<::PB::Types::PlayerState>(GetArenaForAllocation());
    _impl_.state_ = p;
  }
  return _impl_.state_;
}
inline ::PB::Types::PlayerState* ScenePlayerStatePush::mutable_state() {
  ::PB::Types::PlayerState* _msg = _internal_mutable_state();
  // @@protoc_insertion_point(field_mutable:PB.Town.ScenePlayerStatePush.state)
  return _msg;
}
inline void ScenePlayerStatePush::set_allocated_state(::PB::Types::PlayerState* state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.state_);
  }
  if (state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(state));
    if (message_arena != submessage_arena) {
      state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, state, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.state_ = state;
  // @@protoc_insertion_point(field_set_allocated:PB.Town.ScenePlayerStatePush.state)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Town
}  // namespace PB

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PB::Town::TownPlayerStatePush_MsgId> : ::std::true_type {};
template <> struct is_proto_enum< ::PB::Town::ScenePlayerEnterPush_MsgId> : ::std::true_type {};
template <> struct is_proto_enum< ::PB::Town::ScenePlayerLeavePush_MsgId> : ::std::true_type {};
template <> struct is_proto_enum< ::PB::Town::ScenePlayerStatePush_MsgId> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_client_5ftown_2eproto
