// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_battle.proto

#include "client_battle.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace PB {
namespace Battle {
PROTOBUF_CONSTEXPR BattleInputPush::BattleInputPush(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.battle_id_)*/0u
  , /*decltype(_impl_.client_frame_)*/0u
  , /*decltype(_impl_.client_time_ms_)*/uint64_t{0u}
  , /*decltype(_impl_.input_mask_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BattleInputPushDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BattleInputPushDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BattleInputPushDefaultTypeInternal() {}
  union {
    BattleInputPush _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BattleInputPushDefaultTypeInternal _BattleInputPush_default_instance_;
PROTOBUF_CONSTEXPR BattleSnapshotPush::BattleSnapshotPush(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.world_dump_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.battle_id_)*/0u
  , /*decltype(_impl_.server_frame_)*/0u
  , /*decltype(_impl_.server_time_ms_)*/uint64_t{0u}
  , /*decltype(_impl_.last_processed_client_frame_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BattleSnapshotPushDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BattleSnapshotPushDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BattleSnapshotPushDefaultTypeInternal() {}
  union {
    BattleSnapshotPush _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BattleSnapshotPushDefaultTypeInternal _BattleSnapshotPush_default_instance_;
}  // namespace Battle
}  // namespace PB
namespace PB {
namespace Battle {
bool BattleInputPush_MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 20012:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> BattleInputPush_MsgId_strings[2] = {};

static const char BattleInputPush_MsgId_names[] =
  "Id"
  "None";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry BattleInputPush_MsgId_entries[] = {
  { {BattleInputPush_MsgId_names + 0, 2}, 20012 },
  { {BattleInputPush_MsgId_names + 2, 4}, 0 },
};

static const int BattleInputPush_MsgId_entries_by_number[] = {
  1, // 0 -> None
  0, // 20012 -> Id
};

const std::string& BattleInputPush_MsgId_Name(
    BattleInputPush_MsgId value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          BattleInputPush_MsgId_entries,
          BattleInputPush_MsgId_entries_by_number,
          2, BattleInputPush_MsgId_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      BattleInputPush_MsgId_entries,
      BattleInputPush_MsgId_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     BattleInputPush_MsgId_strings[idx].get();
}
bool BattleInputPush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BattleInputPush_MsgId* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      BattleInputPush_MsgId_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<BattleInputPush_MsgId>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr BattleInputPush_MsgId BattleInputPush::None;
constexpr BattleInputPush_MsgId BattleInputPush::Id;
constexpr BattleInputPush_MsgId BattleInputPush::MsgId_MIN;
constexpr BattleInputPush_MsgId BattleInputPush::MsgId_MAX;
constexpr int BattleInputPush::MsgId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
bool BattleSnapshotPush_MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 20013:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> BattleSnapshotPush_MsgId_strings[2] = {};

static const char BattleSnapshotPush_MsgId_names[] =
  "Id"
  "None";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry BattleSnapshotPush_MsgId_entries[] = {
  { {BattleSnapshotPush_MsgId_names + 0, 2}, 20013 },
  { {BattleSnapshotPush_MsgId_names + 2, 4}, 0 },
};

static const int BattleSnapshotPush_MsgId_entries_by_number[] = {
  1, // 0 -> None
  0, // 20013 -> Id
};

const std::string& BattleSnapshotPush_MsgId_Name(
    BattleSnapshotPush_MsgId value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          BattleSnapshotPush_MsgId_entries,
          BattleSnapshotPush_MsgId_entries_by_number,
          2, BattleSnapshotPush_MsgId_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      BattleSnapshotPush_MsgId_entries,
      BattleSnapshotPush_MsgId_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     BattleSnapshotPush_MsgId_strings[idx].get();
}
bool BattleSnapshotPush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BattleSnapshotPush_MsgId* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      BattleSnapshotPush_MsgId_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<BattleSnapshotPush_MsgId>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr BattleSnapshotPush_MsgId BattleSnapshotPush::None;
constexpr BattleSnapshotPush_MsgId BattleSnapshotPush::Id;
constexpr BattleSnapshotPush_MsgId BattleSnapshotPush::MsgId_MIN;
constexpr BattleSnapshotPush_MsgId BattleSnapshotPush::MsgId_MAX;
constexpr int BattleSnapshotPush::MsgId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class BattleInputPush::_Internal {
 public:
};

BattleInputPush::BattleInputPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.Battle.BattleInputPush)
}
BattleInputPush::BattleInputPush(const BattleInputPush& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  BattleInputPush* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.battle_id_){}
    , decltype(_impl_.client_frame_){}
    , decltype(_impl_.client_time_ms_){}
    , decltype(_impl_.input_mask_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&_impl_.battle_id_, &from._impl_.battle_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.input_mask_) -
    reinterpret_cast<char*>(&_impl_.battle_id_)) + sizeof(_impl_.input_mask_));
  // @@protoc_insertion_point(copy_constructor:PB.Battle.BattleInputPush)
}

inline void BattleInputPush::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.battle_id_){0u}
    , decltype(_impl_.client_frame_){0u}
    , decltype(_impl_.client_time_ms_){uint64_t{0u}}
    , decltype(_impl_.input_mask_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BattleInputPush::~BattleInputPush() {
  // @@protoc_insertion_point(destructor:PB.Battle.BattleInputPush)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BattleInputPush::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BattleInputPush::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BattleInputPush::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.Battle.BattleInputPush)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.battle_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.input_mask_) -
      reinterpret_cast<char*>(&_impl_.battle_id_)) + sizeof(_impl_.input_mask_));
  _internal_metadata_.Clear<std::string>();
}

const char* BattleInputPush::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 battle_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.battle_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 client_frame = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.client_frame_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 input_mask = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.input_mask_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 client_time_ms = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.client_time_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BattleInputPush::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.Battle.BattleInputPush)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 battle_id = 1;
  if (this->_internal_battle_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_battle_id(), target);
  }

  // uint32 client_frame = 2;
  if (this->_internal_client_frame() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_client_frame(), target);
  }

  // uint32 input_mask = 3;
  if (this->_internal_input_mask() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_input_mask(), target);
  }

  // uint64 client_time_ms = 4;
  if (this->_internal_client_time_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_client_time_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.Battle.BattleInputPush)
  return target;
}

size_t BattleInputPush::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.Battle.BattleInputPush)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 battle_id = 1;
  if (this->_internal_battle_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_battle_id());
  }

  // uint32 client_frame = 2;
  if (this->_internal_client_frame() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_client_frame());
  }

  // uint64 client_time_ms = 4;
  if (this->_internal_client_time_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_client_time_ms());
  }

  // uint32 input_mask = 3;
  if (this->_internal_input_mask() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_input_mask());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BattleInputPush::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const BattleInputPush*>(
      &from));
}

void BattleInputPush::MergeFrom(const BattleInputPush& from) {
  BattleInputPush* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.Battle.BattleInputPush)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_battle_id() != 0) {
    _this->_internal_set_battle_id(from._internal_battle_id());
  }
  if (from._internal_client_frame() != 0) {
    _this->_internal_set_client_frame(from._internal_client_frame());
  }
  if (from._internal_client_time_ms() != 0) {
    _this->_internal_set_client_time_ms(from._internal_client_time_ms());
  }
  if (from._internal_input_mask() != 0) {
    _this->_internal_set_input_mask(from._internal_input_mask());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void BattleInputPush::CopyFrom(const BattleInputPush& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.Battle.BattleInputPush)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BattleInputPush::IsInitialized() const {
  return true;
}

void BattleInputPush::InternalSwap(BattleInputPush* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BattleInputPush, _impl_.input_mask_)
      + sizeof(BattleInputPush::_impl_.input_mask_)
      - PROTOBUF_FIELD_OFFSET(BattleInputPush, _impl_.battle_id_)>(
          reinterpret_cast<char*>(&_impl_.battle_id_),
          reinterpret_cast<char*>(&other->_impl_.battle_id_));
}

std::string BattleInputPush::GetTypeName() const {
  return "PB.Battle.BattleInputPush";
}


// ===================================================================

class BattleSnapshotPush::_Internal {
 public:
};

BattleSnapshotPush::BattleSnapshotPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.Battle.BattleSnapshotPush)
}
BattleSnapshotPush::BattleSnapshotPush(const BattleSnapshotPush& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  BattleSnapshotPush* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.world_dump_){}
    , decltype(_impl_.battle_id_){}
    , decltype(_impl_.server_frame_){}
    , decltype(_impl_.server_time_ms_){}
    , decltype(_impl_.last_processed_client_frame_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.world_dump_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.world_dump_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_world_dump().empty()) {
    _this->_impl_.world_dump_.Set(from._internal_world_dump(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.battle_id_, &from._impl_.battle_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.last_processed_client_frame_) -
    reinterpret_cast<char*>(&_impl_.battle_id_)) + sizeof(_impl_.last_processed_client_frame_));
  // @@protoc_insertion_point(copy_constructor:PB.Battle.BattleSnapshotPush)
}

inline void BattleSnapshotPush::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.world_dump_){}
    , decltype(_impl_.battle_id_){0u}
    , decltype(_impl_.server_frame_){0u}
    , decltype(_impl_.server_time_ms_){uint64_t{0u}}
    , decltype(_impl_.last_processed_client_frame_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.world_dump_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.world_dump_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

BattleSnapshotPush::~BattleSnapshotPush() {
  // @@protoc_insertion_point(destructor:PB.Battle.BattleSnapshotPush)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BattleSnapshotPush::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.world_dump_.Destroy();
}

void BattleSnapshotPush::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BattleSnapshotPush::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.Battle.BattleSnapshotPush)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.world_dump_.ClearToEmpty();
  ::memset(&_impl_.battle_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.last_processed_client_frame_) -
      reinterpret_cast<char*>(&_impl_.battle_id_)) + sizeof(_impl_.last_processed_client_frame_));
  _internal_metadata_.Clear<std::string>();
}

const char* BattleSnapshotPush::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 battle_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.battle_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 server_frame = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.server_frame_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 server_time_ms = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.server_time_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes world_dump = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_world_dump();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 last_processed_client_frame = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.last_processed_client_frame_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BattleSnapshotPush::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.Battle.BattleSnapshotPush)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 battle_id = 1;
  if (this->_internal_battle_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_battle_id(), target);
  }

  // uint32 server_frame = 2;
  if (this->_internal_server_frame() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_server_frame(), target);
  }

  // uint64 server_time_ms = 3;
  if (this->_internal_server_time_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_server_time_ms(), target);
  }

  // bytes world_dump = 4;
  if (!this->_internal_world_dump().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_world_dump(), target);
  }

  // uint32 last_processed_client_frame = 5;
  if (this->_internal_last_processed_client_frame() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_last_processed_client_frame(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.Battle.BattleSnapshotPush)
  return target;
}

size_t BattleSnapshotPush::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.Battle.BattleSnapshotPush)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes world_dump = 4;
  if (!this->_internal_world_dump().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_world_dump());
  }

  // uint32 battle_id = 1;
  if (this->_internal_battle_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_battle_id());
  }

  // uint32 server_frame = 2;
  if (this->_internal_server_frame() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_server_frame());
  }

  // uint64 server_time_ms = 3;
  if (this->_internal_server_time_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_server_time_ms());
  }

  // uint32 last_processed_client_frame = 5;
  if (this->_internal_last_processed_client_frame() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_last_processed_client_frame());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BattleSnapshotPush::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const BattleSnapshotPush*>(
      &from));
}

void BattleSnapshotPush::MergeFrom(const BattleSnapshotPush& from) {
  BattleSnapshotPush* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.Battle.BattleSnapshotPush)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_world_dump().empty()) {
    _this->_internal_set_world_dump(from._internal_world_dump());
  }
  if (from._internal_battle_id() != 0) {
    _this->_internal_set_battle_id(from._internal_battle_id());
  }
  if (from._internal_server_frame() != 0) {
    _this->_internal_set_server_frame(from._internal_server_frame());
  }
  if (from._internal_server_time_ms() != 0) {
    _this->_internal_set_server_time_ms(from._internal_server_time_ms());
  }
  if (from._internal_last_processed_client_frame() != 0) {
    _this->_internal_set_last_processed_client_frame(from._internal_last_processed_client_frame());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void BattleSnapshotPush::CopyFrom(const BattleSnapshotPush& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.Battle.BattleSnapshotPush)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BattleSnapshotPush::IsInitialized() const {
  return true;
}

void BattleSnapshotPush::InternalSwap(BattleSnapshotPush* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.world_dump_, lhs_arena,
      &other->_impl_.world_dump_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BattleSnapshotPush, _impl_.last_processed_client_frame_)
      + sizeof(BattleSnapshotPush::_impl_.last_processed_client_frame_)
      - PROTOBUF_FIELD_OFFSET(BattleSnapshotPush, _impl_.battle_id_)>(
          reinterpret_cast<char*>(&_impl_.battle_id_),
          reinterpret_cast<char*>(&other->_impl_.battle_id_));
}

std::string BattleSnapshotPush::GetTypeName() const {
  return "PB.Battle.BattleSnapshotPush";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Battle
}  // namespace PB
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PB::Battle::BattleInputPush*
Arena::CreateMaybeMessage< ::PB::Battle::BattleInputPush >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::Battle::BattleInputPush >(arena);
}
template<> PROTOBUF_NOINLINE ::PB::Battle::BattleSnapshotPush*
Arena::CreateMaybeMessage< ::PB::Battle::BattleSnapshotPush >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::Battle::BattleSnapshotPush >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
