// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_battle.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_client_5fbattle_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_client_5fbattle_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_client_5fbattle_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_client_5fbattle_2eproto {
  static const uint32_t offsets[];
};
namespace PB {
namespace Battle {
class BattleInputPush;
struct BattleInputPushDefaultTypeInternal;
extern BattleInputPushDefaultTypeInternal _BattleInputPush_default_instance_;
class BattleSnapshotPush;
struct BattleSnapshotPushDefaultTypeInternal;
extern BattleSnapshotPushDefaultTypeInternal _BattleSnapshotPush_default_instance_;
}  // namespace Battle
}  // namespace PB
PROTOBUF_NAMESPACE_OPEN
template<> ::PB::Battle::BattleInputPush* Arena::CreateMaybeMessage<::PB::Battle::BattleInputPush>(Arena*);
template<> ::PB::Battle::BattleSnapshotPush* Arena::CreateMaybeMessage<::PB::Battle::BattleSnapshotPush>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PB {
namespace Battle {

enum BattleInputPush_MsgId : int {
  BattleInputPush_MsgId_None = 0,
  BattleInputPush_MsgId_Id = 20012,
  BattleInputPush_MsgId_BattleInputPush_MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  BattleInputPush_MsgId_BattleInputPush_MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool BattleInputPush_MsgId_IsValid(int value);
constexpr BattleInputPush_MsgId BattleInputPush_MsgId_MsgId_MIN = BattleInputPush_MsgId_None;
constexpr BattleInputPush_MsgId BattleInputPush_MsgId_MsgId_MAX = BattleInputPush_MsgId_Id;
constexpr int BattleInputPush_MsgId_MsgId_ARRAYSIZE = BattleInputPush_MsgId_MsgId_MAX + 1;

const std::string& BattleInputPush_MsgId_Name(BattleInputPush_MsgId value);
template<typename T>
inline const std::string& BattleInputPush_MsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, BattleInputPush_MsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function BattleInputPush_MsgId_Name.");
  return BattleInputPush_MsgId_Name(static_cast<BattleInputPush_MsgId>(enum_t_value));
}
bool BattleInputPush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BattleInputPush_MsgId* value);
enum BattleSnapshotPush_MsgId : int {
  BattleSnapshotPush_MsgId_None = 0,
  BattleSnapshotPush_MsgId_Id = 20013,
  BattleSnapshotPush_MsgId_BattleSnapshotPush_MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  BattleSnapshotPush_MsgId_BattleSnapshotPush_MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool BattleSnapshotPush_MsgId_IsValid(int value);
constexpr BattleSnapshotPush_MsgId BattleSnapshotPush_MsgId_MsgId_MIN = BattleSnapshotPush_MsgId_None;
constexpr BattleSnapshotPush_MsgId BattleSnapshotPush_MsgId_MsgId_MAX = BattleSnapshotPush_MsgId_Id;
constexpr int BattleSnapshotPush_MsgId_MsgId_ARRAYSIZE = BattleSnapshotPush_MsgId_MsgId_MAX + 1;

const std::string& BattleSnapshotPush_MsgId_Name(BattleSnapshotPush_MsgId value);
template<typename T>
inline const std::string& BattleSnapshotPush_MsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, BattleSnapshotPush_MsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function BattleSnapshotPush_MsgId_Name.");
  return BattleSnapshotPush_MsgId_Name(static_cast<BattleSnapshotPush_MsgId>(enum_t_value));
}
bool BattleSnapshotPush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BattleSnapshotPush_MsgId* value);
// ===================================================================

class BattleInputPush final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Battle.BattleInputPush) */ {
 public:
  inline BattleInputPush() : BattleInputPush(nullptr) {}
  ~BattleInputPush() override;
  explicit PROTOBUF_CONSTEXPR BattleInputPush(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BattleInputPush(const BattleInputPush& from);
  BattleInputPush(BattleInputPush&& from) noexcept
    : BattleInputPush() {
    *this = ::std::move(from);
  }

  inline BattleInputPush& operator=(const BattleInputPush& from) {
    CopyFrom(from);
    return *this;
  }
  inline BattleInputPush& operator=(BattleInputPush&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const BattleInputPush& default_instance() {
    return *internal_default_instance();
  }
  static inline const BattleInputPush* internal_default_instance() {
    return reinterpret_cast<const BattleInputPush*>(
               &_BattleInputPush_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BattleInputPush& a, BattleInputPush& b) {
    a.Swap(&b);
  }
  inline void Swap(BattleInputPush* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BattleInputPush* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BattleInputPush* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BattleInputPush>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const BattleInputPush& from);
  void MergeFrom(const BattleInputPush& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BattleInputPush* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Battle.BattleInputPush";
  }
  protected:
  explicit BattleInputPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef BattleInputPush_MsgId MsgId;
  static constexpr MsgId None =
    BattleInputPush_MsgId_None;
  static constexpr MsgId Id =
    BattleInputPush_MsgId_Id;
  static inline bool MsgId_IsValid(int value) {
    return BattleInputPush_MsgId_IsValid(value);
  }
  static constexpr MsgId MsgId_MIN =
    BattleInputPush_MsgId_MsgId_MIN;
  static constexpr MsgId MsgId_MAX =
    BattleInputPush_MsgId_MsgId_MAX;
  static constexpr int MsgId_ARRAYSIZE =
    BattleInputPush_MsgId_MsgId_ARRAYSIZE;
  template<typename T>
  static inline const std::string& MsgId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgId_Name.");
    return BattleInputPush_MsgId_Name(enum_t_value);
  }
  static inline bool MsgId_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MsgId* value) {
    return BattleInputPush_MsgId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kBattleIdFieldNumber = 1,
    kClientFrameFieldNumber = 2,
    kClientTimeMsFieldNumber = 4,
    kInputMaskFieldNumber = 3,
  };
  // uint32 battle_id = 1;
  void clear_battle_id();
  uint32_t battle_id() const;
  void set_battle_id(uint32_t value);
  private:
  uint32_t _internal_battle_id() const;
  void _internal_set_battle_id(uint32_t value);
  public:

  // uint32 client_frame = 2;
  void clear_client_frame();
  uint32_t client_frame() const;
  void set_client_frame(uint32_t value);
  private:
  uint32_t _internal_client_frame() const;
  void _internal_set_client_frame(uint32_t value);
  public:

  // uint64 client_time_ms = 4;
  void clear_client_time_ms();
  uint64_t client_time_ms() const;
  void set_client_time_ms(uint64_t value);
  private:
  uint64_t _internal_client_time_ms() const;
  void _internal_set_client_time_ms(uint64_t value);
  public:

  // uint32 input_mask = 3;
  void clear_input_mask();
  uint32_t input_mask() const;
  void set_input_mask(uint32_t value);
  private:
  uint32_t _internal_input_mask() const;
  void _internal_set_input_mask(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Battle.BattleInputPush)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t battle_id_;
    uint32_t client_frame_;
    uint64_t client_time_ms_;
    uint32_t input_mask_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5fbattle_2eproto;
};
// -------------------------------------------------------------------

class BattleSnapshotPush final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Battle.BattleSnapshotPush) */ {
 public:
  inline BattleSnapshotPush() : BattleSnapshotPush(nullptr) {}
  ~BattleSnapshotPush() override;
  explicit PROTOBUF_CONSTEXPR BattleSnapshotPush(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BattleSnapshotPush(const BattleSnapshotPush& from);
  BattleSnapshotPush(BattleSnapshotPush&& from) noexcept
    : BattleSnapshotPush() {
    *this = ::std::move(from);
  }

  inline BattleSnapshotPush& operator=(const BattleSnapshotPush& from) {
    CopyFrom(from);
    return *this;
  }
  inline BattleSnapshotPush& operator=(BattleSnapshotPush&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const BattleSnapshotPush& default_instance() {
    return *internal_default_instance();
  }
  static inline const BattleSnapshotPush* internal_default_instance() {
    return reinterpret_cast<const BattleSnapshotPush*>(
               &_BattleSnapshotPush_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BattleSnapshotPush& a, BattleSnapshotPush& b) {
    a.Swap(&b);
  }
  inline void Swap(BattleSnapshotPush* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BattleSnapshotPush* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BattleSnapshotPush* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BattleSnapshotPush>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const BattleSnapshotPush& from);
  void MergeFrom(const BattleSnapshotPush& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BattleSnapshotPush* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Battle.BattleSnapshotPush";
  }
  protected:
  explicit BattleSnapshotPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef BattleSnapshotPush_MsgId MsgId;
  static constexpr MsgId None =
    BattleSnapshotPush_MsgId_None;
  static constexpr MsgId Id =
    BattleSnapshotPush_MsgId_Id;
  static inline bool MsgId_IsValid(int value) {
    return BattleSnapshotPush_MsgId_IsValid(value);
  }
  static constexpr MsgId MsgId_MIN =
    BattleSnapshotPush_MsgId_MsgId_MIN;
  static constexpr MsgId MsgId_MAX =
    BattleSnapshotPush_MsgId_MsgId_MAX;
  static constexpr int MsgId_ARRAYSIZE =
    BattleSnapshotPush_MsgId_MsgId_ARRAYSIZE;
  template<typename T>
  static inline const std::string& MsgId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgId_Name.");
    return BattleSnapshotPush_MsgId_Name(enum_t_value);
  }
  static inline bool MsgId_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MsgId* value) {
    return BattleSnapshotPush_MsgId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kWorldDumpFieldNumber = 4,
    kBattleIdFieldNumber = 1,
    kServerFrameFieldNumber = 2,
    kServerTimeMsFieldNumber = 3,
    kLastProcessedClientFrameFieldNumber = 5,
  };
  // bytes world_dump = 4;
  void clear_world_dump();
  const std::string& world_dump() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_world_dump(ArgT0&& arg0, ArgT... args);
  std::string* mutable_world_dump();
  PROTOBUF_NODISCARD std::string* release_world_dump();
  void set_allocated_world_dump(std::string* world_dump);
  private:
  const std::string& _internal_world_dump() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_world_dump(const std::string& value);
  std::string* _internal_mutable_world_dump();
  public:

  // uint32 battle_id = 1;
  void clear_battle_id();
  uint32_t battle_id() const;
  void set_battle_id(uint32_t value);
  private:
  uint32_t _internal_battle_id() const;
  void _internal_set_battle_id(uint32_t value);
  public:

  // uint32 server_frame = 2;
  void clear_server_frame();
  uint32_t server_frame() const;
  void set_server_frame(uint32_t value);
  private:
  uint32_t _internal_server_frame() const;
  void _internal_set_server_frame(uint32_t value);
  public:

  // uint64 server_time_ms = 3;
  void clear_server_time_ms();
  uint64_t server_time_ms() const;
  void set_server_time_ms(uint64_t value);
  private:
  uint64_t _internal_server_time_ms() const;
  void _internal_set_server_time_ms(uint64_t value);
  public:

  // uint32 last_processed_client_frame = 5;
  void clear_last_processed_client_frame();
  uint32_t last_processed_client_frame() const;
  void set_last_processed_client_frame(uint32_t value);
  private:
  uint32_t _internal_last_processed_client_frame() const;
  void _internal_set_last_processed_client_frame(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Battle.BattleSnapshotPush)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr world_dump_;
    uint32_t battle_id_;
    uint32_t server_frame_;
    uint64_t server_time_ms_;
    uint32_t last_processed_client_frame_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5fbattle_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BattleInputPush

// uint32 battle_id = 1;
inline void BattleInputPush::clear_battle_id() {
  _impl_.battle_id_ = 0u;
}
inline uint32_t BattleInputPush::_internal_battle_id() const {
  return _impl_.battle_id_;
}
inline uint32_t BattleInputPush::battle_id() const {
  // @@protoc_insertion_point(field_get:PB.Battle.BattleInputPush.battle_id)
  return _internal_battle_id();
}
inline void BattleInputPush::_internal_set_battle_id(uint32_t value) {
  
  _impl_.battle_id_ = value;
}
inline void BattleInputPush::set_battle_id(uint32_t value) {
  _internal_set_battle_id(value);
  // @@protoc_insertion_point(field_set:PB.Battle.BattleInputPush.battle_id)
}

// uint32 client_frame = 2;
inline void BattleInputPush::clear_client_frame() {
  _impl_.client_frame_ = 0u;
}
inline uint32_t BattleInputPush::_internal_client_frame() const {
  return _impl_.client_frame_;
}
inline uint32_t BattleInputPush::client_frame() const {
  // @@protoc_insertion_point(field_get:PB.Battle.BattleInputPush.client_frame)
  return _internal_client_frame();
}
inline void BattleInputPush::_internal_set_client_frame(uint32_t value) {
  
  _impl_.client_frame_ = value;
}
inline void BattleInputPush::set_client_frame(uint32_t value) {
  _internal_set_client_frame(value);
  // @@protoc_insertion_point(field_set:PB.Battle.BattleInputPush.client_frame)
}

// uint32 input_mask = 3;
inline void BattleInputPush::clear_input_mask() {
  _impl_.input_mask_ = 0u;
}
inline uint32_t BattleInputPush::_internal_input_mask() const {
  return _impl_.input_mask_;
}
inline uint32_t BattleInputPush::input_mask() const {
  // @@protoc_insertion_point(field_get:PB.Battle.BattleInputPush.input_mask)
  return _internal_input_mask();
}
inline void BattleInputPush::_internal_set_input_mask(uint32_t value) {
  
  _impl_.input_mask_ = value;
}
inline void BattleInputPush::set_input_mask(uint32_t value) {
  _internal_set_input_mask(value);
  // @@protoc_insertion_point(field_set:PB.Battle.BattleInputPush.input_mask)
}

// uint64 client_time_ms = 4;
inline void BattleInputPush::clear_client_time_ms() {
  _impl_.client_time_ms_ = uint64_t{0u};
}
inline uint64_t BattleInputPush::_internal_client_time_ms() const {
  return _impl_.client_time_ms_;
}
inline uint64_t BattleInputPush::client_time_ms() const {
  // @@protoc_insertion_point(field_get:PB.Battle.BattleInputPush.client_time_ms)
  return _internal_client_time_ms();
}
inline void BattleInputPush::_internal_set_client_time_ms(uint64_t value) {
  
  _impl_.client_time_ms_ = value;
}
inline void BattleInputPush::set_client_time_ms(uint64_t value) {
  _internal_set_client_time_ms(value);
  // @@protoc_insertion_point(field_set:PB.Battle.BattleInputPush.client_time_ms)
}

// -------------------------------------------------------------------

// BattleSnapshotPush

// uint32 battle_id = 1;
inline void BattleSnapshotPush::clear_battle_id() {
  _impl_.battle_id_ = 0u;
}
inline uint32_t BattleSnapshotPush::_internal_battle_id() const {
  return _impl_.battle_id_;
}
inline uint32_t BattleSnapshotPush::battle_id() const {
  // @@protoc_insertion_point(field_get:PB.Battle.BattleSnapshotPush.battle_id)
  return _internal_battle_id();
}
inline void BattleSnapshotPush::_internal_set_battle_id(uint32_t value) {
  
  _impl_.battle_id_ = value;
}
inline void BattleSnapshotPush::set_battle_id(uint32_t value) {
  _internal_set_battle_id(value);
  // @@protoc_insertion_point(field_set:PB.Battle.BattleSnapshotPush.battle_id)
}

// uint32 server_frame = 2;
inline void BattleSnapshotPush::clear_server_frame() {
  _impl_.server_frame_ = 0u;
}
inline uint32_t BattleSnapshotPush::_internal_server_frame() const {
  return _impl_.server_frame_;
}
inline uint32_t BattleSnapshotPush::server_frame() const {
  // @@protoc_insertion_point(field_get:PB.Battle.BattleSnapshotPush.server_frame)
  return _internal_server_frame();
}
inline void BattleSnapshotPush::_internal_set_server_frame(uint32_t value) {
  
  _impl_.server_frame_ = value;
}
inline void BattleSnapshotPush::set_server_frame(uint32_t value) {
  _internal_set_server_frame(value);
  // @@protoc_insertion_point(field_set:PB.Battle.BattleSnapshotPush.server_frame)
}

// uint64 server_time_ms = 3;
inline void BattleSnapshotPush::clear_server_time_ms() {
  _impl_.server_time_ms_ = uint64_t{0u};
}
inline uint64_t BattleSnapshotPush::_internal_server_time_ms() const {
  return _impl_.server_time_ms_;
}
inline uint64_t BattleSnapshotPush::server_time_ms() const {
  // @@protoc_insertion_point(field_get:PB.Battle.BattleSnapshotPush.server_time_ms)
  return _internal_server_time_ms();
}
inline void BattleSnapshotPush::_internal_set_server_time_ms(uint64_t value) {
  
  _impl_.server_time_ms_ = value;
}
inline void BattleSnapshotPush::set_server_time_ms(uint64_t value) {
  _internal_set_server_time_ms(value);
  // @@protoc_insertion_point(field_set:PB.Battle.BattleSnapshotPush.server_time_ms)
}

// bytes world_dump = 4;
inline void BattleSnapshotPush::clear_world_dump() {
  _impl_.world_dump_.ClearToEmpty();
}
inline const std::string& BattleSnapshotPush::world_dump() const {
  // @@protoc_insertion_point(field_get:PB.Battle.BattleSnapshotPush.world_dump)
  return _internal_world_dump();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BattleSnapshotPush::set_world_dump(ArgT0&& arg0, ArgT... args) {
 
 _impl_.world_dump_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PB.Battle.BattleSnapshotPush.world_dump)
}
inline std::string* BattleSnapshotPush::mutable_world_dump() {
  std::string* _s = _internal_mutable_world_dump();
  // @@protoc_insertion_point(field_mutable:PB.Battle.BattleSnapshotPush.world_dump)
  return _s;
}
inline const std::string& BattleSnapshotPush::_internal_world_dump() const {
  return _impl_.world_dump_.Get();
}
inline void BattleSnapshotPush::_internal_set_world_dump(const std::string& value) {
  
  _impl_.world_dump_.Set(value, GetArenaForAllocation());
}
inline std::string* BattleSnapshotPush::_internal_mutable_world_dump() {
  
  return _impl_.world_dump_.Mutable(GetArenaForAllocation());
}
inline std::string* BattleSnapshotPush::release_world_dump() {
  // @@protoc_insertion_point(field_release:PB.Battle.BattleSnapshotPush.world_dump)
  return _impl_.world_dump_.Release();
}
inline void BattleSnapshotPush::set_allocated_world_dump(std::string* world_dump) {
  if (world_dump != nullptr) {
    
  } else {
    
  }
  _impl_.world_dump_.SetAllocated(world_dump, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.world_dump_.IsDefault()) {
    _impl_.world_dump_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PB.Battle.BattleSnapshotPush.world_dump)
}

// uint32 last_processed_client_frame = 5;
inline void BattleSnapshotPush::clear_last_processed_client_frame() {
  _impl_.last_processed_client_frame_ = 0u;
}
inline uint32_t BattleSnapshotPush::_internal_last_processed_client_frame() const {
  return _impl_.last_processed_client_frame_;
}
inline uint32_t BattleSnapshotPush::last_processed_client_frame() const {
  // @@protoc_insertion_point(field_get:PB.Battle.BattleSnapshotPush.last_processed_client_frame)
  return _internal_last_processed_client_frame();
}
inline void BattleSnapshotPush::_internal_set_last_processed_client_frame(uint32_t value) {
  
  _impl_.last_processed_client_frame_ = value;
}
inline void BattleSnapshotPush::set_last_processed_client_frame(uint32_t value) {
  _internal_set_last_processed_client_frame(value);
  // @@protoc_insertion_point(field_set:PB.Battle.BattleSnapshotPush.last_processed_client_frame)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Battle
}  // namespace PB

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PB::Battle::BattleInputPush_MsgId> : ::std::true_type {};
template <> struct is_proto_enum< ::PB::Battle::BattleSnapshotPush_MsgId> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_client_5fbattle_2eproto
