// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_town.proto

#include "client_town.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace PB {
namespace Town {
PROTOBUF_CONSTEXPR TownPlayerStatePush::TownPlayerStatePush(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.state_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TownPlayerStatePushDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TownPlayerStatePushDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TownPlayerStatePushDefaultTypeInternal() {}
  union {
    TownPlayerStatePush _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TownPlayerStatePushDefaultTypeInternal _TownPlayerStatePush_default_instance_;
PROTOBUF_CONSTEXPR ScenePlayerEnterPush::ScenePlayerEnterPush(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.state_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ScenePlayerEnterPushDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ScenePlayerEnterPushDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ScenePlayerEnterPushDefaultTypeInternal() {}
  union {
    ScenePlayerEnterPush _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ScenePlayerEnterPushDefaultTypeInternal _ScenePlayerEnterPush_default_instance_;
PROTOBUF_CONSTEXPR ScenePlayerLeavePush::ScenePlayerLeavePush(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.player_id_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ScenePlayerLeavePushDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ScenePlayerLeavePushDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ScenePlayerLeavePushDefaultTypeInternal() {}
  union {
    ScenePlayerLeavePush _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ScenePlayerLeavePushDefaultTypeInternal _ScenePlayerLeavePush_default_instance_;
PROTOBUF_CONSTEXPR ScenePlayerStatePush::ScenePlayerStatePush(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.state_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ScenePlayerStatePushDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ScenePlayerStatePushDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ScenePlayerStatePushDefaultTypeInternal() {}
  union {
    ScenePlayerStatePush _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ScenePlayerStatePushDefaultTypeInternal _ScenePlayerStatePush_default_instance_;
}  // namespace Town
}  // namespace PB
namespace PB {
namespace Town {
bool TownPlayerStatePush_MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 30000:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> TownPlayerStatePush_MsgId_strings[2] = {};

static const char TownPlayerStatePush_MsgId_names[] =
  "Id"
  "None";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry TownPlayerStatePush_MsgId_entries[] = {
  { {TownPlayerStatePush_MsgId_names + 0, 2}, 30000 },
  { {TownPlayerStatePush_MsgId_names + 2, 4}, 0 },
};

static const int TownPlayerStatePush_MsgId_entries_by_number[] = {
  1, // 0 -> None
  0, // 30000 -> Id
};

const std::string& TownPlayerStatePush_MsgId_Name(
    TownPlayerStatePush_MsgId value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          TownPlayerStatePush_MsgId_entries,
          TownPlayerStatePush_MsgId_entries_by_number,
          2, TownPlayerStatePush_MsgId_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      TownPlayerStatePush_MsgId_entries,
      TownPlayerStatePush_MsgId_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     TownPlayerStatePush_MsgId_strings[idx].get();
}
bool TownPlayerStatePush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TownPlayerStatePush_MsgId* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      TownPlayerStatePush_MsgId_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<TownPlayerStatePush_MsgId>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr TownPlayerStatePush_MsgId TownPlayerStatePush::None;
constexpr TownPlayerStatePush_MsgId TownPlayerStatePush::Id;
constexpr TownPlayerStatePush_MsgId TownPlayerStatePush::MsgId_MIN;
constexpr TownPlayerStatePush_MsgId TownPlayerStatePush::MsgId_MAX;
constexpr int TownPlayerStatePush::MsgId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
bool ScenePlayerEnterPush_MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 30001:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> ScenePlayerEnterPush_MsgId_strings[2] = {};

static const char ScenePlayerEnterPush_MsgId_names[] =
  "Id"
  "None";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry ScenePlayerEnterPush_MsgId_entries[] = {
  { {ScenePlayerEnterPush_MsgId_names + 0, 2}, 30001 },
  { {ScenePlayerEnterPush_MsgId_names + 2, 4}, 0 },
};

static const int ScenePlayerEnterPush_MsgId_entries_by_number[] = {
  1, // 0 -> None
  0, // 30001 -> Id
};

const std::string& ScenePlayerEnterPush_MsgId_Name(
    ScenePlayerEnterPush_MsgId value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          ScenePlayerEnterPush_MsgId_entries,
          ScenePlayerEnterPush_MsgId_entries_by_number,
          2, ScenePlayerEnterPush_MsgId_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      ScenePlayerEnterPush_MsgId_entries,
      ScenePlayerEnterPush_MsgId_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     ScenePlayerEnterPush_MsgId_strings[idx].get();
}
bool ScenePlayerEnterPush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ScenePlayerEnterPush_MsgId* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      ScenePlayerEnterPush_MsgId_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<ScenePlayerEnterPush_MsgId>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr ScenePlayerEnterPush_MsgId ScenePlayerEnterPush::None;
constexpr ScenePlayerEnterPush_MsgId ScenePlayerEnterPush::Id;
constexpr ScenePlayerEnterPush_MsgId ScenePlayerEnterPush::MsgId_MIN;
constexpr ScenePlayerEnterPush_MsgId ScenePlayerEnterPush::MsgId_MAX;
constexpr int ScenePlayerEnterPush::MsgId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
bool ScenePlayerLeavePush_MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 30002:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> ScenePlayerLeavePush_MsgId_strings[2] = {};

static const char ScenePlayerLeavePush_MsgId_names[] =
  "Id"
  "None";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry ScenePlayerLeavePush_MsgId_entries[] = {
  { {ScenePlayerLeavePush_MsgId_names + 0, 2}, 30002 },
  { {ScenePlayerLeavePush_MsgId_names + 2, 4}, 0 },
};

static const int ScenePlayerLeavePush_MsgId_entries_by_number[] = {
  1, // 0 -> None
  0, // 30002 -> Id
};

const std::string& ScenePlayerLeavePush_MsgId_Name(
    ScenePlayerLeavePush_MsgId value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          ScenePlayerLeavePush_MsgId_entries,
          ScenePlayerLeavePush_MsgId_entries_by_number,
          2, ScenePlayerLeavePush_MsgId_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      ScenePlayerLeavePush_MsgId_entries,
      ScenePlayerLeavePush_MsgId_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     ScenePlayerLeavePush_MsgId_strings[idx].get();
}
bool ScenePlayerLeavePush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ScenePlayerLeavePush_MsgId* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      ScenePlayerLeavePush_MsgId_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<ScenePlayerLeavePush_MsgId>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr ScenePlayerLeavePush_MsgId ScenePlayerLeavePush::None;
constexpr ScenePlayerLeavePush_MsgId ScenePlayerLeavePush::Id;
constexpr ScenePlayerLeavePush_MsgId ScenePlayerLeavePush::MsgId_MIN;
constexpr ScenePlayerLeavePush_MsgId ScenePlayerLeavePush::MsgId_MAX;
constexpr int ScenePlayerLeavePush::MsgId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
bool ScenePlayerStatePush_MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 30003:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> ScenePlayerStatePush_MsgId_strings[2] = {};

static const char ScenePlayerStatePush_MsgId_names[] =
  "Id"
  "None";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry ScenePlayerStatePush_MsgId_entries[] = {
  { {ScenePlayerStatePush_MsgId_names + 0, 2}, 30003 },
  { {ScenePlayerStatePush_MsgId_names + 2, 4}, 0 },
};

static const int ScenePlayerStatePush_MsgId_entries_by_number[] = {
  1, // 0 -> None
  0, // 30003 -> Id
};

const std::string& ScenePlayerStatePush_MsgId_Name(
    ScenePlayerStatePush_MsgId value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          ScenePlayerStatePush_MsgId_entries,
          ScenePlayerStatePush_MsgId_entries_by_number,
          2, ScenePlayerStatePush_MsgId_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      ScenePlayerStatePush_MsgId_entries,
      ScenePlayerStatePush_MsgId_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     ScenePlayerStatePush_MsgId_strings[idx].get();
}
bool ScenePlayerStatePush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ScenePlayerStatePush_MsgId* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      ScenePlayerStatePush_MsgId_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<ScenePlayerStatePush_MsgId>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr ScenePlayerStatePush_MsgId ScenePlayerStatePush::None;
constexpr ScenePlayerStatePush_MsgId ScenePlayerStatePush::Id;
constexpr ScenePlayerStatePush_MsgId ScenePlayerStatePush::MsgId_MIN;
constexpr ScenePlayerStatePush_MsgId ScenePlayerStatePush::MsgId_MAX;
constexpr int ScenePlayerStatePush::MsgId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class TownPlayerStatePush::_Internal {
 public:
  static const ::PB::Types::PlayerState& state(const TownPlayerStatePush* msg);
};

const ::PB::Types::PlayerState&
TownPlayerStatePush::_Internal::state(const TownPlayerStatePush* msg) {
  return *msg->_impl_.state_;
}
void TownPlayerStatePush::clear_state() {
  if (GetArenaForAllocation() == nullptr && _impl_.state_ != nullptr) {
    delete _impl_.state_;
  }
  _impl_.state_ = nullptr;
}
TownPlayerStatePush::TownPlayerStatePush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.Town.TownPlayerStatePush)
}
TownPlayerStatePush::TownPlayerStatePush(const TownPlayerStatePush& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  TownPlayerStatePush* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.state_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_state()) {
    _this->_impl_.state_ = new ::PB::Types::PlayerState(*from._impl_.state_);
  }
  // @@protoc_insertion_point(copy_constructor:PB.Town.TownPlayerStatePush)
}

inline void TownPlayerStatePush::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.state_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TownPlayerStatePush::~TownPlayerStatePush() {
  // @@protoc_insertion_point(destructor:PB.Town.TownPlayerStatePush)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TownPlayerStatePush::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.state_;
}

void TownPlayerStatePush::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TownPlayerStatePush::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.Town.TownPlayerStatePush)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.state_ != nullptr) {
    delete _impl_.state_;
  }
  _impl_.state_ = nullptr;
  _internal_metadata_.Clear<std::string>();
}

const char* TownPlayerStatePush::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .PB.Types.PlayerState state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_state(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TownPlayerStatePush::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.Town.TownPlayerStatePush)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .PB.Types.PlayerState state = 1;
  if (this->_internal_has_state()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::state(this),
        _Internal::state(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.Town.TownPlayerStatePush)
  return target;
}

size_t TownPlayerStatePush::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.Town.TownPlayerStatePush)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .PB.Types.PlayerState state = 1;
  if (this->_internal_has_state()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.state_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TownPlayerStatePush::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const TownPlayerStatePush*>(
      &from));
}

void TownPlayerStatePush::MergeFrom(const TownPlayerStatePush& from) {
  TownPlayerStatePush* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.Town.TownPlayerStatePush)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_state()) {
    _this->_internal_mutable_state()->::PB::Types::PlayerState::MergeFrom(
        from._internal_state());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void TownPlayerStatePush::CopyFrom(const TownPlayerStatePush& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.Town.TownPlayerStatePush)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TownPlayerStatePush::IsInitialized() const {
  return true;
}

void TownPlayerStatePush::InternalSwap(TownPlayerStatePush* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.state_, other->_impl_.state_);
}

std::string TownPlayerStatePush::GetTypeName() const {
  return "PB.Town.TownPlayerStatePush";
}


// ===================================================================

class ScenePlayerEnterPush::_Internal {
 public:
  static const ::PB::Types::PlayerState& state(const ScenePlayerEnterPush* msg);
};

const ::PB::Types::PlayerState&
ScenePlayerEnterPush::_Internal::state(const ScenePlayerEnterPush* msg) {
  return *msg->_impl_.state_;
}
void ScenePlayerEnterPush::clear_state() {
  if (GetArenaForAllocation() == nullptr && _impl_.state_ != nullptr) {
    delete _impl_.state_;
  }
  _impl_.state_ = nullptr;
}
ScenePlayerEnterPush::ScenePlayerEnterPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.Town.ScenePlayerEnterPush)
}
ScenePlayerEnterPush::ScenePlayerEnterPush(const ScenePlayerEnterPush& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  ScenePlayerEnterPush* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.state_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_state()) {
    _this->_impl_.state_ = new ::PB::Types::PlayerState(*from._impl_.state_);
  }
  // @@protoc_insertion_point(copy_constructor:PB.Town.ScenePlayerEnterPush)
}

inline void ScenePlayerEnterPush::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.state_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ScenePlayerEnterPush::~ScenePlayerEnterPush() {
  // @@protoc_insertion_point(destructor:PB.Town.ScenePlayerEnterPush)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ScenePlayerEnterPush::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.state_;
}

void ScenePlayerEnterPush::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ScenePlayerEnterPush::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.Town.ScenePlayerEnterPush)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.state_ != nullptr) {
    delete _impl_.state_;
  }
  _impl_.state_ = nullptr;
  _internal_metadata_.Clear<std::string>();
}

const char* ScenePlayerEnterPush::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .PB.Types.PlayerState state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_state(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ScenePlayerEnterPush::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.Town.ScenePlayerEnterPush)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .PB.Types.PlayerState state = 1;
  if (this->_internal_has_state()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::state(this),
        _Internal::state(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.Town.ScenePlayerEnterPush)
  return target;
}

size_t ScenePlayerEnterPush::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.Town.ScenePlayerEnterPush)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .PB.Types.PlayerState state = 1;
  if (this->_internal_has_state()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.state_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ScenePlayerEnterPush::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const ScenePlayerEnterPush*>(
      &from));
}

void ScenePlayerEnterPush::MergeFrom(const ScenePlayerEnterPush& from) {
  ScenePlayerEnterPush* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.Town.ScenePlayerEnterPush)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_state()) {
    _this->_internal_mutable_state()->::PB::Types::PlayerState::MergeFrom(
        from._internal_state());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void ScenePlayerEnterPush::CopyFrom(const ScenePlayerEnterPush& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.Town.ScenePlayerEnterPush)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScenePlayerEnterPush::IsInitialized() const {
  return true;
}

void ScenePlayerEnterPush::InternalSwap(ScenePlayerEnterPush* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.state_, other->_impl_.state_);
}

std::string ScenePlayerEnterPush::GetTypeName() const {
  return "PB.Town.ScenePlayerEnterPush";
}


// ===================================================================

class ScenePlayerLeavePush::_Internal {
 public:
};

ScenePlayerLeavePush::ScenePlayerLeavePush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.Town.ScenePlayerLeavePush)
}
ScenePlayerLeavePush::ScenePlayerLeavePush(const ScenePlayerLeavePush& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  ScenePlayerLeavePush* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.player_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _this->_impl_.player_id_ = from._impl_.player_id_;
  // @@protoc_insertion_point(copy_constructor:PB.Town.ScenePlayerLeavePush)
}

inline void ScenePlayerLeavePush::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.player_id_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ScenePlayerLeavePush::~ScenePlayerLeavePush() {
  // @@protoc_insertion_point(destructor:PB.Town.ScenePlayerLeavePush)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ScenePlayerLeavePush::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ScenePlayerLeavePush::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ScenePlayerLeavePush::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.Town.ScenePlayerLeavePush)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.player_id_ = int64_t{0};
  _internal_metadata_.Clear<std::string>();
}

const char* ScenePlayerLeavePush::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 player_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.player_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ScenePlayerLeavePush::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.Town.ScenePlayerLeavePush)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 player_id = 1;
  if (this->_internal_player_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_player_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.Town.ScenePlayerLeavePush)
  return target;
}

size_t ScenePlayerLeavePush::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.Town.ScenePlayerLeavePush)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 player_id = 1;
  if (this->_internal_player_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_player_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ScenePlayerLeavePush::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const ScenePlayerLeavePush*>(
      &from));
}

void ScenePlayerLeavePush::MergeFrom(const ScenePlayerLeavePush& from) {
  ScenePlayerLeavePush* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.Town.ScenePlayerLeavePush)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_player_id() != 0) {
    _this->_internal_set_player_id(from._internal_player_id());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void ScenePlayerLeavePush::CopyFrom(const ScenePlayerLeavePush& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.Town.ScenePlayerLeavePush)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScenePlayerLeavePush::IsInitialized() const {
  return true;
}

void ScenePlayerLeavePush::InternalSwap(ScenePlayerLeavePush* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.player_id_, other->_impl_.player_id_);
}

std::string ScenePlayerLeavePush::GetTypeName() const {
  return "PB.Town.ScenePlayerLeavePush";
}


// ===================================================================

class ScenePlayerStatePush::_Internal {
 public:
  static const ::PB::Types::PlayerState& state(const ScenePlayerStatePush* msg);
};

const ::PB::Types::PlayerState&
ScenePlayerStatePush::_Internal::state(const ScenePlayerStatePush* msg) {
  return *msg->_impl_.state_;
}
void ScenePlayerStatePush::clear_state() {
  if (GetArenaForAllocation() == nullptr && _impl_.state_ != nullptr) {
    delete _impl_.state_;
  }
  _impl_.state_ = nullptr;
}
ScenePlayerStatePush::ScenePlayerStatePush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.Town.ScenePlayerStatePush)
}
ScenePlayerStatePush::ScenePlayerStatePush(const ScenePlayerStatePush& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  ScenePlayerStatePush* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.state_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_state()) {
    _this->_impl_.state_ = new ::PB::Types::PlayerState(*from._impl_.state_);
  }
  // @@protoc_insertion_point(copy_constructor:PB.Town.ScenePlayerStatePush)
}

inline void ScenePlayerStatePush::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.state_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ScenePlayerStatePush::~ScenePlayerStatePush() {
  // @@protoc_insertion_point(destructor:PB.Town.ScenePlayerStatePush)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ScenePlayerStatePush::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.state_;
}

void ScenePlayerStatePush::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ScenePlayerStatePush::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.Town.ScenePlayerStatePush)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.state_ != nullptr) {
    delete _impl_.state_;
  }
  _impl_.state_ = nullptr;
  _internal_metadata_.Clear<std::string>();
}

const char* ScenePlayerStatePush::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .PB.Types.PlayerState state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_state(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ScenePlayerStatePush::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.Town.ScenePlayerStatePush)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .PB.Types.PlayerState state = 1;
  if (this->_internal_has_state()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::state(this),
        _Internal::state(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.Town.ScenePlayerStatePush)
  return target;
}

size_t ScenePlayerStatePush::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.Town.ScenePlayerStatePush)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .PB.Types.PlayerState state = 1;
  if (this->_internal_has_state()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.state_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ScenePlayerStatePush::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const ScenePlayerStatePush*>(
      &from));
}

void ScenePlayerStatePush::MergeFrom(const ScenePlayerStatePush& from) {
  ScenePlayerStatePush* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.Town.ScenePlayerStatePush)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_state()) {
    _this->_internal_mutable_state()->::PB::Types::PlayerState::MergeFrom(
        from._internal_state());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void ScenePlayerStatePush::CopyFrom(const ScenePlayerStatePush& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.Town.ScenePlayerStatePush)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScenePlayerStatePush::IsInitialized() const {
  return true;
}

void ScenePlayerStatePush::InternalSwap(ScenePlayerStatePush* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.state_, other->_impl_.state_);
}

std::string ScenePlayerStatePush::GetTypeName() const {
  return "PB.Town.ScenePlayerStatePush";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Town
}  // namespace PB
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PB::Town::TownPlayerStatePush*
Arena::CreateMaybeMessage< ::PB::Town::TownPlayerStatePush >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::Town::TownPlayerStatePush >(arena);
}
template<> PROTOBUF_NOINLINE ::PB::Town::ScenePlayerEnterPush*
Arena::CreateMaybeMessage< ::PB::Town::ScenePlayerEnterPush >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::Town::ScenePlayerEnterPush >(arena);
}
template<> PROTOBUF_NOINLINE ::PB::Town::ScenePlayerLeavePush*
Arena::CreateMaybeMessage< ::PB::Town::ScenePlayerLeavePush >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::Town::ScenePlayerLeavePush >(arena);
}
template<> PROTOBUF_NOINLINE ::PB::Town::ScenePlayerStatePush*
Arena::CreateMaybeMessage< ::PB::Town::ScenePlayerStatePush >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::Town::ScenePlayerStatePush >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
