// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_types.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_5ftypes_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_game_5ftypes_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_game_5ftypes_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_game_5ftypes_2eproto {
  static const uint32_t offsets[];
};
namespace PB {
namespace Types {
class AccountInfo;
struct AccountInfoDefaultTypeInternal;
extern AccountInfoDefaultTypeInternal _AccountInfo_default_instance_;
class BattlePlayerSpec;
struct BattlePlayerSpecDefaultTypeInternal;
extern BattlePlayerSpecDefaultTypeInternal _BattlePlayerSpec_default_instance_;
class CharacterInfo;
struct CharacterInfoDefaultTypeInternal;
extern CharacterInfoDefaultTypeInternal _CharacterInfo_default_instance_;
class EnchantProp;
struct EnchantPropDefaultTypeInternal;
extern EnchantPropDefaultTypeInternal _EnchantProp_default_instance_;
class EquipmentInfo;
struct EquipmentInfoDefaultTypeInternal;
extern EquipmentInfoDefaultTypeInternal _EquipmentInfo_default_instance_;
class InventoryInfo;
struct InventoryInfoDefaultTypeInternal;
extern InventoryInfoDefaultTypeInternal _InventoryInfo_default_instance_;
class ItemInfo;
struct ItemInfoDefaultTypeInternal;
extern ItemInfoDefaultTypeInternal _ItemInfo_default_instance_;
class PlayerState;
struct PlayerStateDefaultTypeInternal;
extern PlayerStateDefaultTypeInternal _PlayerState_default_instance_;
class SceneInfo;
struct SceneInfoDefaultTypeInternal;
extern SceneInfoDefaultTypeInternal _SceneInfo_default_instance_;
class ServerConfig;
struct ServerConfigDefaultTypeInternal;
extern ServerConfigDefaultTypeInternal _ServerConfig_default_instance_;
}  // namespace Types
}  // namespace PB
PROTOBUF_NAMESPACE_OPEN
template<> ::PB::Types::AccountInfo* Arena::CreateMaybeMessage<::PB::Types::AccountInfo>(Arena*);
template<> ::PB::Types::BattlePlayerSpec* Arena::CreateMaybeMessage<::PB::Types::BattlePlayerSpec>(Arena*);
template<> ::PB::Types::CharacterInfo* Arena::CreateMaybeMessage<::PB::Types::CharacterInfo>(Arena*);
template<> ::PB::Types::EnchantProp* Arena::CreateMaybeMessage<::PB::Types::EnchantProp>(Arena*);
template<> ::PB::Types::EquipmentInfo* Arena::CreateMaybeMessage<::PB::Types::EquipmentInfo>(Arena*);
template<> ::PB::Types::InventoryInfo* Arena::CreateMaybeMessage<::PB::Types::InventoryInfo>(Arena*);
template<> ::PB::Types::ItemInfo* Arena::CreateMaybeMessage<::PB::Types::ItemInfo>(Arena*);
template<> ::PB::Types::PlayerState* Arena::CreateMaybeMessage<::PB::Types::PlayerState>(Arena*);
template<> ::PB::Types::SceneInfo* Arena::CreateMaybeMessage<::PB::Types::SceneInfo>(Arena*);
template<> ::PB::Types::ServerConfig* Arena::CreateMaybeMessage<::PB::Types::ServerConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PB {
namespace Types {

enum SceneEnterType : int {
  None = 0,
  Map = 1,
  Home = 2,
  SceneEnterType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  SceneEnterType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool SceneEnterType_IsValid(int value);
constexpr SceneEnterType SceneEnterType_MIN = None;
constexpr SceneEnterType SceneEnterType_MAX = Home;
constexpr int SceneEnterType_ARRAYSIZE = SceneEnterType_MAX + 1;

const std::string& SceneEnterType_Name(SceneEnterType value);
template<typename T>
inline const std::string& SceneEnterType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SceneEnterType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SceneEnterType_Name.");
  return SceneEnterType_Name(static_cast<SceneEnterType>(enum_t_value));
}
bool SceneEnterType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SceneEnterType* value);
// ===================================================================

class ServerConfig final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Types.ServerConfig) */ {
 public:
  inline ServerConfig() : ServerConfig(nullptr) {}
  ~ServerConfig() override;
  explicit PROTOBUF_CONSTEXPR ServerConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerConfig(const ServerConfig& from);
  ServerConfig(ServerConfig&& from) noexcept
    : ServerConfig() {
    *this = ::std::move(from);
  }

  inline ServerConfig& operator=(const ServerConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerConfig& operator=(ServerConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ServerConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerConfig* internal_default_instance() {
    return reinterpret_cast<const ServerConfig*>(
               &_ServerConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ServerConfig& a, ServerConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerConfig>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ServerConfig& from);
  void MergeFrom(const ServerConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ServerConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Types.ServerConfig";
  }
  protected:
  explicit ServerConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMaxCharacterCountFieldNumber = 1,
  };
  // int32 max_character_count = 1;
  void clear_max_character_count();
  int32_t max_character_count() const;
  void set_max_character_count(int32_t value);
  private:
  int32_t _internal_max_character_count() const;
  void _internal_set_max_character_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Types.ServerConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t max_character_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class AccountInfo final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Types.AccountInfo) */ {
 public:
  inline AccountInfo() : AccountInfo(nullptr) {}
  ~AccountInfo() override;
  explicit PROTOBUF_CONSTEXPR AccountInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AccountInfo(const AccountInfo& from);
  AccountInfo(AccountInfo&& from) noexcept
    : AccountInfo() {
    *this = ::std::move(from);
  }

  inline AccountInfo& operator=(const AccountInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountInfo& operator=(AccountInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const AccountInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const AccountInfo* internal_default_instance() {
    return reinterpret_cast<const AccountInfo*>(
               &_AccountInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AccountInfo& a, AccountInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AccountInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AccountInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const AccountInfo& from);
  void MergeFrom(const AccountInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AccountInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Types.AccountInfo";
  }
  protected:
  explicit AccountInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountFieldNumber = 2,
    kNicknameFieldNumber = 3,
    kPlayerIdFieldNumber = 1,
  };
  // string account = 2;
  void clear_account();
  const std::string& account() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_account(ArgT0&& arg0, ArgT... args);
  std::string* mutable_account();
  PROTOBUF_NODISCARD std::string* release_account();
  void set_allocated_account(std::string* account);
  private:
  const std::string& _internal_account() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account(const std::string& value);
  std::string* _internal_mutable_account();
  public:

  // string nickname = 3;
  void clear_nickname();
  const std::string& nickname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nickname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nickname();
  PROTOBUF_NODISCARD std::string* release_nickname();
  void set_allocated_nickname(std::string* nickname);
  private:
  const std::string& _internal_nickname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const std::string& value);
  std::string* _internal_mutable_nickname();
  public:

  // int64 player_id = 1;
  void clear_player_id();
  int64_t player_id() const;
  void set_player_id(int64_t value);
  private:
  int64_t _internal_player_id() const;
  void _internal_set_player_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Types.AccountInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nickname_;
    int64_t player_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class EnchantProp final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Types.EnchantProp) */ {
 public:
  inline EnchantProp() : EnchantProp(nullptr) {}
  ~EnchantProp() override;
  explicit PROTOBUF_CONSTEXPR EnchantProp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EnchantProp(const EnchantProp& from);
  EnchantProp(EnchantProp&& from) noexcept
    : EnchantProp() {
    *this = ::std::move(from);
  }

  inline EnchantProp& operator=(const EnchantProp& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnchantProp& operator=(EnchantProp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const EnchantProp& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnchantProp* internal_default_instance() {
    return reinterpret_cast<const EnchantProp*>(
               &_EnchantProp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(EnchantProp& a, EnchantProp& b) {
    a.Swap(&b);
  }
  inline void Swap(EnchantProp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnchantProp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EnchantProp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EnchantProp>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const EnchantProp& from);
  void MergeFrom(const EnchantProp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EnchantProp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Types.EnchantProp";
  }
  protected:
  explicit EnchantProp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAttrIdFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // int32 attr_id = 1;
  void clear_attr_id();
  int32_t attr_id() const;
  void set_attr_id(int32_t value);
  private:
  int32_t _internal_attr_id() const;
  void _internal_set_attr_id(int32_t value);
  public:

  // int32 value = 2;
  void clear_value();
  int32_t value() const;
  void set_value(int32_t value);
  private:
  int32_t _internal_value() const;
  void _internal_set_value(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Types.EnchantProp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t attr_id_;
    int32_t value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class EquipmentInfo final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Types.EquipmentInfo) */ {
 public:
  inline EquipmentInfo() : EquipmentInfo(nullptr) {}
  ~EquipmentInfo() override;
  explicit PROTOBUF_CONSTEXPR EquipmentInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EquipmentInfo(const EquipmentInfo& from);
  EquipmentInfo(EquipmentInfo&& from) noexcept
    : EquipmentInfo() {
    *this = ::std::move(from);
  }

  inline EquipmentInfo& operator=(const EquipmentInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline EquipmentInfo& operator=(EquipmentInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const EquipmentInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const EquipmentInfo* internal_default_instance() {
    return reinterpret_cast<const EquipmentInfo*>(
               &_EquipmentInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(EquipmentInfo& a, EquipmentInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(EquipmentInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EquipmentInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EquipmentInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EquipmentInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const EquipmentInfo& from);
  void MergeFrom(const EquipmentInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EquipmentInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Types.EquipmentInfo";
  }
  protected:
  explicit EquipmentInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEnchantPropsFieldNumber = 5,
    kIdFieldNumber = 1,
    kConfigIdFieldNumber = 2,
    kEnhanceLevelFieldNumber = 3,
    kRefineLevelFieldNumber = 4,
    kSlotFieldNumber = 6,
  };
  // repeated .PB.Types.EnchantProp enchant_props = 5;
  int enchant_props_size() const;
  private:
  int _internal_enchant_props_size() const;
  public:
  void clear_enchant_props();
  ::PB::Types::EnchantProp* mutable_enchant_props(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::EnchantProp >*
      mutable_enchant_props();
  private:
  const ::PB::Types::EnchantProp& _internal_enchant_props(int index) const;
  ::PB::Types::EnchantProp* _internal_add_enchant_props();
  public:
  const ::PB::Types::EnchantProp& enchant_props(int index) const;
  ::PB::Types::EnchantProp* add_enchant_props();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::EnchantProp >&
      enchant_props() const;

  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // int64 config_id = 2;
  void clear_config_id();
  int64_t config_id() const;
  void set_config_id(int64_t value);
  private:
  int64_t _internal_config_id() const;
  void _internal_set_config_id(int64_t value);
  public:

  // int32 enhance_level = 3;
  void clear_enhance_level();
  int32_t enhance_level() const;
  void set_enhance_level(int32_t value);
  private:
  int32_t _internal_enhance_level() const;
  void _internal_set_enhance_level(int32_t value);
  public:

  // int32 refine_level = 4;
  void clear_refine_level();
  int32_t refine_level() const;
  void set_refine_level(int32_t value);
  private:
  int32_t _internal_refine_level() const;
  void _internal_set_refine_level(int32_t value);
  public:

  // int32 slot = 6;
  void clear_slot();
  int32_t slot() const;
  void set_slot(int32_t value);
  private:
  int32_t _internal_slot() const;
  void _internal_set_slot(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Types.EquipmentInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::EnchantProp > enchant_props_;
    int64_t id_;
    int64_t config_id_;
    int32_t enhance_level_;
    int32_t refine_level_;
    int32_t slot_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class ItemInfo final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Types.ItemInfo) */ {
 public:
  inline ItemInfo() : ItemInfo(nullptr) {}
  ~ItemInfo() override;
  explicit PROTOBUF_CONSTEXPR ItemInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ItemInfo(const ItemInfo& from);
  ItemInfo(ItemInfo&& from) noexcept
    : ItemInfo() {
    *this = ::std::move(from);
  }

  inline ItemInfo& operator=(const ItemInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ItemInfo& operator=(ItemInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ItemInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ItemInfo* internal_default_instance() {
    return reinterpret_cast<const ItemInfo*>(
               &_ItemInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ItemInfo& a, ItemInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ItemInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ItemInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ItemInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ItemInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ItemInfo& from);
  void MergeFrom(const ItemInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ItemInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Types.ItemInfo";
  }
  protected:
  explicit ItemInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kConfigIdFieldNumber = 2,
    kCountFieldNumber = 3,
  };
  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // int64 config_id = 2;
  void clear_config_id();
  int64_t config_id() const;
  void set_config_id(int64_t value);
  private:
  int64_t _internal_config_id() const;
  void _internal_set_config_id(int64_t value);
  public:

  // int32 count = 3;
  void clear_count();
  int32_t count() const;
  void set_count(int32_t value);
  private:
  int32_t _internal_count() const;
  void _internal_set_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Types.ItemInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t id_;
    int64_t config_id_;
    int32_t count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class InventoryInfo final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Types.InventoryInfo) */ {
 public:
  inline InventoryInfo() : InventoryInfo(nullptr) {}
  ~InventoryInfo() override;
  explicit PROTOBUF_CONSTEXPR InventoryInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InventoryInfo(const InventoryInfo& from);
  InventoryInfo(InventoryInfo&& from) noexcept
    : InventoryInfo() {
    *this = ::std::move(from);
  }

  inline InventoryInfo& operator=(const InventoryInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline InventoryInfo& operator=(InventoryInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const InventoryInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const InventoryInfo* internal_default_instance() {
    return reinterpret_cast<const InventoryInfo*>(
               &_InventoryInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(InventoryInfo& a, InventoryInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(InventoryInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InventoryInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InventoryInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InventoryInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const InventoryInfo& from);
  void MergeFrom(const InventoryInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(InventoryInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Types.InventoryInfo";
  }
  protected:
  explicit InventoryInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 1,
    kEquipmentsFieldNumber = 2,
  };
  // repeated .PB.Types.ItemInfo items = 1;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::PB::Types::ItemInfo* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::ItemInfo >*
      mutable_items();
  private:
  const ::PB::Types::ItemInfo& _internal_items(int index) const;
  ::PB::Types::ItemInfo* _internal_add_items();
  public:
  const ::PB::Types::ItemInfo& items(int index) const;
  ::PB::Types::ItemInfo* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::ItemInfo >&
      items() const;

  // repeated .PB.Types.EquipmentInfo equipments = 2;
  int equipments_size() const;
  private:
  int _internal_equipments_size() const;
  public:
  void clear_equipments();
  ::PB::Types::EquipmentInfo* mutable_equipments(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::EquipmentInfo >*
      mutable_equipments();
  private:
  const ::PB::Types::EquipmentInfo& _internal_equipments(int index) const;
  ::PB::Types::EquipmentInfo* _internal_add_equipments();
  public:
  const ::PB::Types::EquipmentInfo& equipments(int index) const;
  ::PB::Types::EquipmentInfo* add_equipments();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::EquipmentInfo >&
      equipments() const;

  // @@protoc_insertion_point(class_scope:PB.Types.InventoryInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::ItemInfo > items_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::EquipmentInfo > equipments_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class CharacterInfo final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Types.CharacterInfo) */ {
 public:
  inline CharacterInfo() : CharacterInfo(nullptr) {}
  ~CharacterInfo() override;
  explicit PROTOBUF_CONSTEXPR CharacterInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CharacterInfo(const CharacterInfo& from);
  CharacterInfo(CharacterInfo&& from) noexcept
    : CharacterInfo() {
    *this = ::std::move(from);
  }

  inline CharacterInfo& operator=(const CharacterInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline CharacterInfo& operator=(CharacterInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const CharacterInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const CharacterInfo* internal_default_instance() {
    return reinterpret_cast<const CharacterInfo*>(
               &_CharacterInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(CharacterInfo& a, CharacterInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(CharacterInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CharacterInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CharacterInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CharacterInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const CharacterInfo& from);
  void MergeFrom(const CharacterInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CharacterInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Types.CharacterInfo";
  }
  protected:
  explicit CharacterInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kCharacterIdFieldNumber = 1,
    kClassIdFieldNumber = 3,
    kGenderFieldNumber = 4,
    kExpFieldNumber = 6,
    kGoldFieldNumber = 7,
    kLevelFieldNumber = 5,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int64 character_id = 1;
  void clear_character_id();
  int64_t character_id() const;
  void set_character_id(int64_t value);
  private:
  int64_t _internal_character_id() const;
  void _internal_set_character_id(int64_t value);
  public:

  // int32 class_id = 3;
  void clear_class_id();
  int32_t class_id() const;
  void set_class_id(int32_t value);
  private:
  int32_t _internal_class_id() const;
  void _internal_set_class_id(int32_t value);
  public:

  // int32 gender = 4;
  void clear_gender();
  int32_t gender() const;
  void set_gender(int32_t value);
  private:
  int32_t _internal_gender() const;
  void _internal_set_gender(int32_t value);
  public:

  // int64 exp = 6;
  void clear_exp();
  int64_t exp() const;
  void set_exp(int64_t value);
  private:
  int64_t _internal_exp() const;
  void _internal_set_exp(int64_t value);
  public:

  // int64 gold = 7;
  void clear_gold();
  int64_t gold() const;
  void set_gold(int64_t value);
  private:
  int64_t _internal_gold() const;
  void _internal_set_gold(int64_t value);
  public:

  // int32 level = 5;
  void clear_level();
  int32_t level() const;
  void set_level(int32_t value);
  private:
  int32_t _internal_level() const;
  void _internal_set_level(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Types.CharacterInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int64_t character_id_;
    int32_t class_id_;
    int32_t gender_;
    int64_t exp_;
    int64_t gold_;
    int32_t level_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class PlayerState final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Types.PlayerState) */ {
 public:
  inline PlayerState() : PlayerState(nullptr) {}
  ~PlayerState() override;
  explicit PROTOBUF_CONSTEXPR PlayerState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerState(const PlayerState& from);
  PlayerState(PlayerState&& from) noexcept
    : PlayerState() {
    *this = ::std::move(from);
  }

  inline PlayerState& operator=(const PlayerState& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerState& operator=(PlayerState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const PlayerState& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerState* internal_default_instance() {
    return reinterpret_cast<const PlayerState*>(
               &_PlayerState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(PlayerState& a, PlayerState& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerState>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const PlayerState& from);
  void MergeFrom(const PlayerState& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PlayerState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Types.PlayerState";
  }
  protected:
  explicit PlayerState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 5,
    kNameFieldNumber = 7,
    kPlayerIdFieldNumber = 1,
    kPosXFieldNumber = 2,
    kPosYFieldNumber = 3,
    kHpFieldNumber = 4,
    kClassIdFieldNumber = 6,
    kPosZFieldNumber = 8,
    kFacingFieldNumber = 9,
    kMovingFieldNumber = 10,
    kVelXFieldNumber = 11,
    kVelYFieldNumber = 12,
  };
  // string state = 5;
  void clear_state();
  const std::string& state() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_state(ArgT0&& arg0, ArgT... args);
  std::string* mutable_state();
  PROTOBUF_NODISCARD std::string* release_state();
  void set_allocated_state(std::string* state);
  private:
  const std::string& _internal_state() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_state(const std::string& value);
  std::string* _internal_mutable_state();
  public:

  // string name = 7;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int64 player_id = 1;
  void clear_player_id();
  int64_t player_id() const;
  void set_player_id(int64_t value);
  private:
  int64_t _internal_player_id() const;
  void _internal_set_player_id(int64_t value);
  public:

  // float pos_x = 2;
  void clear_pos_x();
  float pos_x() const;
  void set_pos_x(float value);
  private:
  float _internal_pos_x() const;
  void _internal_set_pos_x(float value);
  public:

  // float pos_y = 3;
  void clear_pos_y();
  float pos_y() const;
  void set_pos_y(float value);
  private:
  float _internal_pos_y() const;
  void _internal_set_pos_y(float value);
  public:

  // int32 hp = 4;
  void clear_hp();
  int32_t hp() const;
  void set_hp(int32_t value);
  private:
  int32_t _internal_hp() const;
  void _internal_set_hp(int32_t value);
  public:

  // int32 class_id = 6;
  void clear_class_id();
  int32_t class_id() const;
  void set_class_id(int32_t value);
  private:
  int32_t _internal_class_id() const;
  void _internal_set_class_id(int32_t value);
  public:

  // float pos_z = 8;
  void clear_pos_z();
  float pos_z() const;
  void set_pos_z(float value);
  private:
  float _internal_pos_z() const;
  void _internal_set_pos_z(float value);
  public:

  // int32 facing = 9;
  void clear_facing();
  int32_t facing() const;
  void set_facing(int32_t value);
  private:
  int32_t _internal_facing() const;
  void _internal_set_facing(int32_t value);
  public:

  // bool moving = 10;
  void clear_moving();
  bool moving() const;
  void set_moving(bool value);
  private:
  bool _internal_moving() const;
  void _internal_set_moving(bool value);
  public:

  // float vel_x = 11;
  void clear_vel_x();
  float vel_x() const;
  void set_vel_x(float value);
  private:
  float _internal_vel_x() const;
  void _internal_set_vel_x(float value);
  public:

  // float vel_y = 12;
  void clear_vel_y();
  float vel_y() const;
  void set_vel_y(float value);
  private:
  float _internal_vel_y() const;
  void _internal_set_vel_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Types.PlayerState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr state_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int64_t player_id_;
    float pos_x_;
    float pos_y_;
    int32_t hp_;
    int32_t class_id_;
    float pos_z_;
    int32_t facing_;
    bool moving_;
    float vel_x_;
    float vel_y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class SceneInfo final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Types.SceneInfo) */ {
 public:
  inline SceneInfo() : SceneInfo(nullptr) {}
  ~SceneInfo() override;
  explicit PROTOBUF_CONSTEXPR SceneInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SceneInfo(const SceneInfo& from);
  SceneInfo(SceneInfo&& from) noexcept
    : SceneInfo() {
    *this = ::std::move(from);
  }

  inline SceneInfo& operator=(const SceneInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline SceneInfo& operator=(SceneInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const SceneInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const SceneInfo* internal_default_instance() {
    return reinterpret_cast<const SceneInfo*>(
               &_SceneInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(SceneInfo& a, SceneInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(SceneInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SceneInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SceneInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SceneInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const SceneInfo& from);
  void MergeFrom(const SceneInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SceneInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Types.SceneInfo";
  }
  protected:
  explicit SceneInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kMapIdFieldNumber = 2,
    kOwnerUidFieldNumber = 3,
  };
  // .PB.Types.SceneEnterType type = 1;
  void clear_type();
  ::PB::Types::SceneEnterType type() const;
  void set_type(::PB::Types::SceneEnterType value);
  private:
  ::PB::Types::SceneEnterType _internal_type() const;
  void _internal_set_type(::PB::Types::SceneEnterType value);
  public:

  // uint32 map_id = 2;
  void clear_map_id();
  uint32_t map_id() const;
  void set_map_id(uint32_t value);
  private:
  uint32_t _internal_map_id() const;
  void _internal_set_map_id(uint32_t value);
  public:

  // uint64 owner_uid = 3;
  void clear_owner_uid();
  uint64_t owner_uid() const;
  void set_owner_uid(uint64_t value);
  private:
  uint64_t _internal_owner_uid() const;
  void _internal_set_owner_uid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Types.SceneInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int type_;
    uint32_t map_id_;
    uint64_t owner_uid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class BattlePlayerSpec final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.Types.BattlePlayerSpec) */ {
 public:
  inline BattlePlayerSpec() : BattlePlayerSpec(nullptr) {}
  ~BattlePlayerSpec() override;
  explicit PROTOBUF_CONSTEXPR BattlePlayerSpec(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BattlePlayerSpec(const BattlePlayerSpec& from);
  BattlePlayerSpec(BattlePlayerSpec&& from) noexcept
    : BattlePlayerSpec() {
    *this = ::std::move(from);
  }

  inline BattlePlayerSpec& operator=(const BattlePlayerSpec& from) {
    CopyFrom(from);
    return *this;
  }
  inline BattlePlayerSpec& operator=(BattlePlayerSpec&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const BattlePlayerSpec& default_instance() {
    return *internal_default_instance();
  }
  static inline const BattlePlayerSpec* internal_default_instance() {
    return reinterpret_cast<const BattlePlayerSpec*>(
               &_BattlePlayerSpec_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(BattlePlayerSpec& a, BattlePlayerSpec& b) {
    a.Swap(&b);
  }
  inline void Swap(BattlePlayerSpec* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BattlePlayerSpec* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BattlePlayerSpec* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BattlePlayerSpec>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const BattlePlayerSpec& from);
  void MergeFrom(const BattlePlayerSpec& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BattlePlayerSpec* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.Types.BattlePlayerSpec";
  }
  protected:
  explicit BattlePlayerSpec(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 4,
    kPlayerIdFieldNumber = 2,
    kSessionIdFieldNumber = 1,
    kClassIdFieldNumber = 3,
    kCharacterIdFieldNumber = 5,
  };
  // string name = 4;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int64 player_id = 2;
  void clear_player_id();
  int64_t player_id() const;
  void set_player_id(int64_t value);
  private:
  int64_t _internal_player_id() const;
  void _internal_set_player_id(int64_t value);
  public:

  // uint32 session_id = 1;
  void clear_session_id();
  uint32_t session_id() const;
  void set_session_id(uint32_t value);
  private:
  uint32_t _internal_session_id() const;
  void _internal_set_session_id(uint32_t value);
  public:

  // int32 class_id = 3;
  void clear_class_id();
  int32_t class_id() const;
  void set_class_id(int32_t value);
  private:
  int32_t _internal_class_id() const;
  void _internal_set_class_id(int32_t value);
  public:

  // int64 character_id = 5;
  void clear_character_id();
  int64_t character_id() const;
  void set_character_id(int64_t value);
  private:
  int64_t _internal_character_id() const;
  void _internal_set_character_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.Types.BattlePlayerSpec)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int64_t player_id_;
    uint32_t session_id_;
    int32_t class_id_;
    int64_t character_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5ftypes_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerConfig

// int32 max_character_count = 1;
inline void ServerConfig::clear_max_character_count() {
  _impl_.max_character_count_ = 0;
}
inline int32_t ServerConfig::_internal_max_character_count() const {
  return _impl_.max_character_count_;
}
inline int32_t ServerConfig::max_character_count() const {
  // @@protoc_insertion_point(field_get:PB.Types.ServerConfig.max_character_count)
  return _internal_max_character_count();
}
inline void ServerConfig::_internal_set_max_character_count(int32_t value) {
  
  _impl_.max_character_count_ = value;
}
inline void ServerConfig::set_max_character_count(int32_t value) {
  _internal_set_max_character_count(value);
  // @@protoc_insertion_point(field_set:PB.Types.ServerConfig.max_character_count)
}

// -------------------------------------------------------------------

// AccountInfo

// int64 player_id = 1;
inline void AccountInfo::clear_player_id() {
  _impl_.player_id_ = int64_t{0};
}
inline int64_t AccountInfo::_internal_player_id() const {
  return _impl_.player_id_;
}
inline int64_t AccountInfo::player_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.AccountInfo.player_id)
  return _internal_player_id();
}
inline void AccountInfo::_internal_set_player_id(int64_t value) {
  
  _impl_.player_id_ = value;
}
inline void AccountInfo::set_player_id(int64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.AccountInfo.player_id)
}

// string account = 2;
inline void AccountInfo::clear_account() {
  _impl_.account_.ClearToEmpty();
}
inline const std::string& AccountInfo::account() const {
  // @@protoc_insertion_point(field_get:PB.Types.AccountInfo.account)
  return _internal_account();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AccountInfo::set_account(ArgT0&& arg0, ArgT... args) {
 
 _impl_.account_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PB.Types.AccountInfo.account)
}
inline std::string* AccountInfo::mutable_account() {
  std::string* _s = _internal_mutable_account();
  // @@protoc_insertion_point(field_mutable:PB.Types.AccountInfo.account)
  return _s;
}
inline const std::string& AccountInfo::_internal_account() const {
  return _impl_.account_.Get();
}
inline void AccountInfo::_internal_set_account(const std::string& value) {
  
  _impl_.account_.Set(value, GetArenaForAllocation());
}
inline std::string* AccountInfo::_internal_mutable_account() {
  
  return _impl_.account_.Mutable(GetArenaForAllocation());
}
inline std::string* AccountInfo::release_account() {
  // @@protoc_insertion_point(field_release:PB.Types.AccountInfo.account)
  return _impl_.account_.Release();
}
inline void AccountInfo::set_allocated_account(std::string* account) {
  if (account != nullptr) {
    
  } else {
    
  }
  _impl_.account_.SetAllocated(account, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.account_.IsDefault()) {
    _impl_.account_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PB.Types.AccountInfo.account)
}

// string nickname = 3;
inline void AccountInfo::clear_nickname() {
  _impl_.nickname_.ClearToEmpty();
}
inline const std::string& AccountInfo::nickname() const {
  // @@protoc_insertion_point(field_get:PB.Types.AccountInfo.nickname)
  return _internal_nickname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AccountInfo::set_nickname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.nickname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PB.Types.AccountInfo.nickname)
}
inline std::string* AccountInfo::mutable_nickname() {
  std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:PB.Types.AccountInfo.nickname)
  return _s;
}
inline const std::string& AccountInfo::_internal_nickname() const {
  return _impl_.nickname_.Get();
}
inline void AccountInfo::_internal_set_nickname(const std::string& value) {
  
  _impl_.nickname_.Set(value, GetArenaForAllocation());
}
inline std::string* AccountInfo::_internal_mutable_nickname() {
  
  return _impl_.nickname_.Mutable(GetArenaForAllocation());
}
inline std::string* AccountInfo::release_nickname() {
  // @@protoc_insertion_point(field_release:PB.Types.AccountInfo.nickname)
  return _impl_.nickname_.Release();
}
inline void AccountInfo::set_allocated_nickname(std::string* nickname) {
  if (nickname != nullptr) {
    
  } else {
    
  }
  _impl_.nickname_.SetAllocated(nickname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nickname_.IsDefault()) {
    _impl_.nickname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PB.Types.AccountInfo.nickname)
}

// -------------------------------------------------------------------

// EnchantProp

// int32 attr_id = 1;
inline void EnchantProp::clear_attr_id() {
  _impl_.attr_id_ = 0;
}
inline int32_t EnchantProp::_internal_attr_id() const {
  return _impl_.attr_id_;
}
inline int32_t EnchantProp::attr_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.EnchantProp.attr_id)
  return _internal_attr_id();
}
inline void EnchantProp::_internal_set_attr_id(int32_t value) {
  
  _impl_.attr_id_ = value;
}
inline void EnchantProp::set_attr_id(int32_t value) {
  _internal_set_attr_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.EnchantProp.attr_id)
}

// int32 value = 2;
inline void EnchantProp::clear_value() {
  _impl_.value_ = 0;
}
inline int32_t EnchantProp::_internal_value() const {
  return _impl_.value_;
}
inline int32_t EnchantProp::value() const {
  // @@protoc_insertion_point(field_get:PB.Types.EnchantProp.value)
  return _internal_value();
}
inline void EnchantProp::_internal_set_value(int32_t value) {
  
  _impl_.value_ = value;
}
inline void EnchantProp::set_value(int32_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:PB.Types.EnchantProp.value)
}

// -------------------------------------------------------------------

// EquipmentInfo

// int64 id = 1;
inline void EquipmentInfo::clear_id() {
  _impl_.id_ = int64_t{0};
}
inline int64_t EquipmentInfo::_internal_id() const {
  return _impl_.id_;
}
inline int64_t EquipmentInfo::id() const {
  // @@protoc_insertion_point(field_get:PB.Types.EquipmentInfo.id)
  return _internal_id();
}
inline void EquipmentInfo::_internal_set_id(int64_t value) {
  
  _impl_.id_ = value;
}
inline void EquipmentInfo::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.EquipmentInfo.id)
}

// int64 config_id = 2;
inline void EquipmentInfo::clear_config_id() {
  _impl_.config_id_ = int64_t{0};
}
inline int64_t EquipmentInfo::_internal_config_id() const {
  return _impl_.config_id_;
}
inline int64_t EquipmentInfo::config_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.EquipmentInfo.config_id)
  return _internal_config_id();
}
inline void EquipmentInfo::_internal_set_config_id(int64_t value) {
  
  _impl_.config_id_ = value;
}
inline void EquipmentInfo::set_config_id(int64_t value) {
  _internal_set_config_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.EquipmentInfo.config_id)
}

// int32 enhance_level = 3;
inline void EquipmentInfo::clear_enhance_level() {
  _impl_.enhance_level_ = 0;
}
inline int32_t EquipmentInfo::_internal_enhance_level() const {
  return _impl_.enhance_level_;
}
inline int32_t EquipmentInfo::enhance_level() const {
  // @@protoc_insertion_point(field_get:PB.Types.EquipmentInfo.enhance_level)
  return _internal_enhance_level();
}
inline void EquipmentInfo::_internal_set_enhance_level(int32_t value) {
  
  _impl_.enhance_level_ = value;
}
inline void EquipmentInfo::set_enhance_level(int32_t value) {
  _internal_set_enhance_level(value);
  // @@protoc_insertion_point(field_set:PB.Types.EquipmentInfo.enhance_level)
}

// int32 refine_level = 4;
inline void EquipmentInfo::clear_refine_level() {
  _impl_.refine_level_ = 0;
}
inline int32_t EquipmentInfo::_internal_refine_level() const {
  return _impl_.refine_level_;
}
inline int32_t EquipmentInfo::refine_level() const {
  // @@protoc_insertion_point(field_get:PB.Types.EquipmentInfo.refine_level)
  return _internal_refine_level();
}
inline void EquipmentInfo::_internal_set_refine_level(int32_t value) {
  
  _impl_.refine_level_ = value;
}
inline void EquipmentInfo::set_refine_level(int32_t value) {
  _internal_set_refine_level(value);
  // @@protoc_insertion_point(field_set:PB.Types.EquipmentInfo.refine_level)
}

// repeated .PB.Types.EnchantProp enchant_props = 5;
inline int EquipmentInfo::_internal_enchant_props_size() const {
  return _impl_.enchant_props_.size();
}
inline int EquipmentInfo::enchant_props_size() const {
  return _internal_enchant_props_size();
}
inline void EquipmentInfo::clear_enchant_props() {
  _impl_.enchant_props_.Clear();
}
inline ::PB::Types::EnchantProp* EquipmentInfo::mutable_enchant_props(int index) {
  // @@protoc_insertion_point(field_mutable:PB.Types.EquipmentInfo.enchant_props)
  return _impl_.enchant_props_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::EnchantProp >*
EquipmentInfo::mutable_enchant_props() {
  // @@protoc_insertion_point(field_mutable_list:PB.Types.EquipmentInfo.enchant_props)
  return &_impl_.enchant_props_;
}
inline const ::PB::Types::EnchantProp& EquipmentInfo::_internal_enchant_props(int index) const {
  return _impl_.enchant_props_.Get(index);
}
inline const ::PB::Types::EnchantProp& EquipmentInfo::enchant_props(int index) const {
  // @@protoc_insertion_point(field_get:PB.Types.EquipmentInfo.enchant_props)
  return _internal_enchant_props(index);
}
inline ::PB::Types::EnchantProp* EquipmentInfo::_internal_add_enchant_props() {
  return _impl_.enchant_props_.Add();
}
inline ::PB::Types::EnchantProp* EquipmentInfo::add_enchant_props() {
  ::PB::Types::EnchantProp* _add = _internal_add_enchant_props();
  // @@protoc_insertion_point(field_add:PB.Types.EquipmentInfo.enchant_props)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::EnchantProp >&
EquipmentInfo::enchant_props() const {
  // @@protoc_insertion_point(field_list:PB.Types.EquipmentInfo.enchant_props)
  return _impl_.enchant_props_;
}

// int32 slot = 6;
inline void EquipmentInfo::clear_slot() {
  _impl_.slot_ = 0;
}
inline int32_t EquipmentInfo::_internal_slot() const {
  return _impl_.slot_;
}
inline int32_t EquipmentInfo::slot() const {
  // @@protoc_insertion_point(field_get:PB.Types.EquipmentInfo.slot)
  return _internal_slot();
}
inline void EquipmentInfo::_internal_set_slot(int32_t value) {
  
  _impl_.slot_ = value;
}
inline void EquipmentInfo::set_slot(int32_t value) {
  _internal_set_slot(value);
  // @@protoc_insertion_point(field_set:PB.Types.EquipmentInfo.slot)
}

// -------------------------------------------------------------------

// ItemInfo

// int64 id = 1;
inline void ItemInfo::clear_id() {
  _impl_.id_ = int64_t{0};
}
inline int64_t ItemInfo::_internal_id() const {
  return _impl_.id_;
}
inline int64_t ItemInfo::id() const {
  // @@protoc_insertion_point(field_get:PB.Types.ItemInfo.id)
  return _internal_id();
}
inline void ItemInfo::_internal_set_id(int64_t value) {
  
  _impl_.id_ = value;
}
inline void ItemInfo::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.ItemInfo.id)
}

// int64 config_id = 2;
inline void ItemInfo::clear_config_id() {
  _impl_.config_id_ = int64_t{0};
}
inline int64_t ItemInfo::_internal_config_id() const {
  return _impl_.config_id_;
}
inline int64_t ItemInfo::config_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.ItemInfo.config_id)
  return _internal_config_id();
}
inline void ItemInfo::_internal_set_config_id(int64_t value) {
  
  _impl_.config_id_ = value;
}
inline void ItemInfo::set_config_id(int64_t value) {
  _internal_set_config_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.ItemInfo.config_id)
}

// int32 count = 3;
inline void ItemInfo::clear_count() {
  _impl_.count_ = 0;
}
inline int32_t ItemInfo::_internal_count() const {
  return _impl_.count_;
}
inline int32_t ItemInfo::count() const {
  // @@protoc_insertion_point(field_get:PB.Types.ItemInfo.count)
  return _internal_count();
}
inline void ItemInfo::_internal_set_count(int32_t value) {
  
  _impl_.count_ = value;
}
inline void ItemInfo::set_count(int32_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:PB.Types.ItemInfo.count)
}

// -------------------------------------------------------------------

// InventoryInfo

// repeated .PB.Types.ItemInfo items = 1;
inline int InventoryInfo::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int InventoryInfo::items_size() const {
  return _internal_items_size();
}
inline void InventoryInfo::clear_items() {
  _impl_.items_.Clear();
}
inline ::PB::Types::ItemInfo* InventoryInfo::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:PB.Types.InventoryInfo.items)
  return _impl_.items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::ItemInfo >*
InventoryInfo::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:PB.Types.InventoryInfo.items)
  return &_impl_.items_;
}
inline const ::PB::Types::ItemInfo& InventoryInfo::_internal_items(int index) const {
  return _impl_.items_.Get(index);
}
inline const ::PB::Types::ItemInfo& InventoryInfo::items(int index) const {
  // @@protoc_insertion_point(field_get:PB.Types.InventoryInfo.items)
  return _internal_items(index);
}
inline ::PB::Types::ItemInfo* InventoryInfo::_internal_add_items() {
  return _impl_.items_.Add();
}
inline ::PB::Types::ItemInfo* InventoryInfo::add_items() {
  ::PB::Types::ItemInfo* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:PB.Types.InventoryInfo.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::ItemInfo >&
InventoryInfo::items() const {
  // @@protoc_insertion_point(field_list:PB.Types.InventoryInfo.items)
  return _impl_.items_;
}

// repeated .PB.Types.EquipmentInfo equipments = 2;
inline int InventoryInfo::_internal_equipments_size() const {
  return _impl_.equipments_.size();
}
inline int InventoryInfo::equipments_size() const {
  return _internal_equipments_size();
}
inline void InventoryInfo::clear_equipments() {
  _impl_.equipments_.Clear();
}
inline ::PB::Types::EquipmentInfo* InventoryInfo::mutable_equipments(int index) {
  // @@protoc_insertion_point(field_mutable:PB.Types.InventoryInfo.equipments)
  return _impl_.equipments_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::EquipmentInfo >*
InventoryInfo::mutable_equipments() {
  // @@protoc_insertion_point(field_mutable_list:PB.Types.InventoryInfo.equipments)
  return &_impl_.equipments_;
}
inline const ::PB::Types::EquipmentInfo& InventoryInfo::_internal_equipments(int index) const {
  return _impl_.equipments_.Get(index);
}
inline const ::PB::Types::EquipmentInfo& InventoryInfo::equipments(int index) const {
  // @@protoc_insertion_point(field_get:PB.Types.InventoryInfo.equipments)
  return _internal_equipments(index);
}
inline ::PB::Types::EquipmentInfo* InventoryInfo::_internal_add_equipments() {
  return _impl_.equipments_.Add();
}
inline ::PB::Types::EquipmentInfo* InventoryInfo::add_equipments() {
  ::PB::Types::EquipmentInfo* _add = _internal_add_equipments();
  // @@protoc_insertion_point(field_add:PB.Types.InventoryInfo.equipments)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::EquipmentInfo >&
InventoryInfo::equipments() const {
  // @@protoc_insertion_point(field_list:PB.Types.InventoryInfo.equipments)
  return _impl_.equipments_;
}

// -------------------------------------------------------------------

// CharacterInfo

// int64 character_id = 1;
inline void CharacterInfo::clear_character_id() {
  _impl_.character_id_ = int64_t{0};
}
inline int64_t CharacterInfo::_internal_character_id() const {
  return _impl_.character_id_;
}
inline int64_t CharacterInfo::character_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.CharacterInfo.character_id)
  return _internal_character_id();
}
inline void CharacterInfo::_internal_set_character_id(int64_t value) {
  
  _impl_.character_id_ = value;
}
inline void CharacterInfo::set_character_id(int64_t value) {
  _internal_set_character_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.CharacterInfo.character_id)
}

// string name = 2;
inline void CharacterInfo::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& CharacterInfo::name() const {
  // @@protoc_insertion_point(field_get:PB.Types.CharacterInfo.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CharacterInfo::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PB.Types.CharacterInfo.name)
}
inline std::string* CharacterInfo::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:PB.Types.CharacterInfo.name)
  return _s;
}
inline const std::string& CharacterInfo::_internal_name() const {
  return _impl_.name_.Get();
}
inline void CharacterInfo::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* CharacterInfo::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* CharacterInfo::release_name() {
  // @@protoc_insertion_point(field_release:PB.Types.CharacterInfo.name)
  return _impl_.name_.Release();
}
inline void CharacterInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PB.Types.CharacterInfo.name)
}

// int32 class_id = 3;
inline void CharacterInfo::clear_class_id() {
  _impl_.class_id_ = 0;
}
inline int32_t CharacterInfo::_internal_class_id() const {
  return _impl_.class_id_;
}
inline int32_t CharacterInfo::class_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.CharacterInfo.class_id)
  return _internal_class_id();
}
inline void CharacterInfo::_internal_set_class_id(int32_t value) {
  
  _impl_.class_id_ = value;
}
inline void CharacterInfo::set_class_id(int32_t value) {
  _internal_set_class_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.CharacterInfo.class_id)
}

// int32 gender = 4;
inline void CharacterInfo::clear_gender() {
  _impl_.gender_ = 0;
}
inline int32_t CharacterInfo::_internal_gender() const {
  return _impl_.gender_;
}
inline int32_t CharacterInfo::gender() const {
  // @@protoc_insertion_point(field_get:PB.Types.CharacterInfo.gender)
  return _internal_gender();
}
inline void CharacterInfo::_internal_set_gender(int32_t value) {
  
  _impl_.gender_ = value;
}
inline void CharacterInfo::set_gender(int32_t value) {
  _internal_set_gender(value);
  // @@protoc_insertion_point(field_set:PB.Types.CharacterInfo.gender)
}

// int32 level = 5;
inline void CharacterInfo::clear_level() {
  _impl_.level_ = 0;
}
inline int32_t CharacterInfo::_internal_level() const {
  return _impl_.level_;
}
inline int32_t CharacterInfo::level() const {
  // @@protoc_insertion_point(field_get:PB.Types.CharacterInfo.level)
  return _internal_level();
}
inline void CharacterInfo::_internal_set_level(int32_t value) {
  
  _impl_.level_ = value;
}
inline void CharacterInfo::set_level(int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:PB.Types.CharacterInfo.level)
}

// int64 exp = 6;
inline void CharacterInfo::clear_exp() {
  _impl_.exp_ = int64_t{0};
}
inline int64_t CharacterInfo::_internal_exp() const {
  return _impl_.exp_;
}
inline int64_t CharacterInfo::exp() const {
  // @@protoc_insertion_point(field_get:PB.Types.CharacterInfo.exp)
  return _internal_exp();
}
inline void CharacterInfo::_internal_set_exp(int64_t value) {
  
  _impl_.exp_ = value;
}
inline void CharacterInfo::set_exp(int64_t value) {
  _internal_set_exp(value);
  // @@protoc_insertion_point(field_set:PB.Types.CharacterInfo.exp)
}

// int64 gold = 7;
inline void CharacterInfo::clear_gold() {
  _impl_.gold_ = int64_t{0};
}
inline int64_t CharacterInfo::_internal_gold() const {
  return _impl_.gold_;
}
inline int64_t CharacterInfo::gold() const {
  // @@protoc_insertion_point(field_get:PB.Types.CharacterInfo.gold)
  return _internal_gold();
}
inline void CharacterInfo::_internal_set_gold(int64_t value) {
  
  _impl_.gold_ = value;
}
inline void CharacterInfo::set_gold(int64_t value) {
  _internal_set_gold(value);
  // @@protoc_insertion_point(field_set:PB.Types.CharacterInfo.gold)
}

// -------------------------------------------------------------------

// PlayerState

// int64 player_id = 1;
inline void PlayerState::clear_player_id() {
  _impl_.player_id_ = int64_t{0};
}
inline int64_t PlayerState::_internal_player_id() const {
  return _impl_.player_id_;
}
inline int64_t PlayerState::player_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.player_id)
  return _internal_player_id();
}
inline void PlayerState::_internal_set_player_id(int64_t value) {
  
  _impl_.player_id_ = value;
}
inline void PlayerState::set_player_id(int64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.player_id)
}

// float pos_x = 2;
inline void PlayerState::clear_pos_x() {
  _impl_.pos_x_ = 0;
}
inline float PlayerState::_internal_pos_x() const {
  return _impl_.pos_x_;
}
inline float PlayerState::pos_x() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.pos_x)
  return _internal_pos_x();
}
inline void PlayerState::_internal_set_pos_x(float value) {
  
  _impl_.pos_x_ = value;
}
inline void PlayerState::set_pos_x(float value) {
  _internal_set_pos_x(value);
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.pos_x)
}

// float pos_y = 3;
inline void PlayerState::clear_pos_y() {
  _impl_.pos_y_ = 0;
}
inline float PlayerState::_internal_pos_y() const {
  return _impl_.pos_y_;
}
inline float PlayerState::pos_y() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.pos_y)
  return _internal_pos_y();
}
inline void PlayerState::_internal_set_pos_y(float value) {
  
  _impl_.pos_y_ = value;
}
inline void PlayerState::set_pos_y(float value) {
  _internal_set_pos_y(value);
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.pos_y)
}

// int32 hp = 4;
inline void PlayerState::clear_hp() {
  _impl_.hp_ = 0;
}
inline int32_t PlayerState::_internal_hp() const {
  return _impl_.hp_;
}
inline int32_t PlayerState::hp() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.hp)
  return _internal_hp();
}
inline void PlayerState::_internal_set_hp(int32_t value) {
  
  _impl_.hp_ = value;
}
inline void PlayerState::set_hp(int32_t value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.hp)
}

// string state = 5;
inline void PlayerState::clear_state() {
  _impl_.state_.ClearToEmpty();
}
inline const std::string& PlayerState::state() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.state)
  return _internal_state();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlayerState::set_state(ArgT0&& arg0, ArgT... args) {
 
 _impl_.state_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.state)
}
inline std::string* PlayerState::mutable_state() {
  std::string* _s = _internal_mutable_state();
  // @@protoc_insertion_point(field_mutable:PB.Types.PlayerState.state)
  return _s;
}
inline const std::string& PlayerState::_internal_state() const {
  return _impl_.state_.Get();
}
inline void PlayerState::_internal_set_state(const std::string& value) {
  
  _impl_.state_.Set(value, GetArenaForAllocation());
}
inline std::string* PlayerState::_internal_mutable_state() {
  
  return _impl_.state_.Mutable(GetArenaForAllocation());
}
inline std::string* PlayerState::release_state() {
  // @@protoc_insertion_point(field_release:PB.Types.PlayerState.state)
  return _impl_.state_.Release();
}
inline void PlayerState::set_allocated_state(std::string* state) {
  if (state != nullptr) {
    
  } else {
    
  }
  _impl_.state_.SetAllocated(state, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.state_.IsDefault()) {
    _impl_.state_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PB.Types.PlayerState.state)
}

// int32 class_id = 6;
inline void PlayerState::clear_class_id() {
  _impl_.class_id_ = 0;
}
inline int32_t PlayerState::_internal_class_id() const {
  return _impl_.class_id_;
}
inline int32_t PlayerState::class_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.class_id)
  return _internal_class_id();
}
inline void PlayerState::_internal_set_class_id(int32_t value) {
  
  _impl_.class_id_ = value;
}
inline void PlayerState::set_class_id(int32_t value) {
  _internal_set_class_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.class_id)
}

// string name = 7;
inline void PlayerState::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& PlayerState::name() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlayerState::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.name)
}
inline std::string* PlayerState::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:PB.Types.PlayerState.name)
  return _s;
}
inline const std::string& PlayerState::_internal_name() const {
  return _impl_.name_.Get();
}
inline void PlayerState::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* PlayerState::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* PlayerState::release_name() {
  // @@protoc_insertion_point(field_release:PB.Types.PlayerState.name)
  return _impl_.name_.Release();
}
inline void PlayerState::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PB.Types.PlayerState.name)
}

// float pos_z = 8;
inline void PlayerState::clear_pos_z() {
  _impl_.pos_z_ = 0;
}
inline float PlayerState::_internal_pos_z() const {
  return _impl_.pos_z_;
}
inline float PlayerState::pos_z() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.pos_z)
  return _internal_pos_z();
}
inline void PlayerState::_internal_set_pos_z(float value) {
  
  _impl_.pos_z_ = value;
}
inline void PlayerState::set_pos_z(float value) {
  _internal_set_pos_z(value);
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.pos_z)
}

// int32 facing = 9;
inline void PlayerState::clear_facing() {
  _impl_.facing_ = 0;
}
inline int32_t PlayerState::_internal_facing() const {
  return _impl_.facing_;
}
inline int32_t PlayerState::facing() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.facing)
  return _internal_facing();
}
inline void PlayerState::_internal_set_facing(int32_t value) {
  
  _impl_.facing_ = value;
}
inline void PlayerState::set_facing(int32_t value) {
  _internal_set_facing(value);
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.facing)
}

// bool moving = 10;
inline void PlayerState::clear_moving() {
  _impl_.moving_ = false;
}
inline bool PlayerState::_internal_moving() const {
  return _impl_.moving_;
}
inline bool PlayerState::moving() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.moving)
  return _internal_moving();
}
inline void PlayerState::_internal_set_moving(bool value) {
  
  _impl_.moving_ = value;
}
inline void PlayerState::set_moving(bool value) {
  _internal_set_moving(value);
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.moving)
}

// float vel_x = 11;
inline void PlayerState::clear_vel_x() {
  _impl_.vel_x_ = 0;
}
inline float PlayerState::_internal_vel_x() const {
  return _impl_.vel_x_;
}
inline float PlayerState::vel_x() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.vel_x)
  return _internal_vel_x();
}
inline void PlayerState::_internal_set_vel_x(float value) {
  
  _impl_.vel_x_ = value;
}
inline void PlayerState::set_vel_x(float value) {
  _internal_set_vel_x(value);
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.vel_x)
}

// float vel_y = 12;
inline void PlayerState::clear_vel_y() {
  _impl_.vel_y_ = 0;
}
inline float PlayerState::_internal_vel_y() const {
  return _impl_.vel_y_;
}
inline float PlayerState::vel_y() const {
  // @@protoc_insertion_point(field_get:PB.Types.PlayerState.vel_y)
  return _internal_vel_y();
}
inline void PlayerState::_internal_set_vel_y(float value) {
  
  _impl_.vel_y_ = value;
}
inline void PlayerState::set_vel_y(float value) {
  _internal_set_vel_y(value);
  // @@protoc_insertion_point(field_set:PB.Types.PlayerState.vel_y)
}

// -------------------------------------------------------------------

// SceneInfo

// .PB.Types.SceneEnterType type = 1;
inline void SceneInfo::clear_type() {
  _impl_.type_ = 0;
}
inline ::PB::Types::SceneEnterType SceneInfo::_internal_type() const {
  return static_cast< ::PB::Types::SceneEnterType >(_impl_.type_);
}
inline ::PB::Types::SceneEnterType SceneInfo::type() const {
  // @@protoc_insertion_point(field_get:PB.Types.SceneInfo.type)
  return _internal_type();
}
inline void SceneInfo::_internal_set_type(::PB::Types::SceneEnterType value) {
  
  _impl_.type_ = value;
}
inline void SceneInfo::set_type(::PB::Types::SceneEnterType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:PB.Types.SceneInfo.type)
}

// uint32 map_id = 2;
inline void SceneInfo::clear_map_id() {
  _impl_.map_id_ = 0u;
}
inline uint32_t SceneInfo::_internal_map_id() const {
  return _impl_.map_id_;
}
inline uint32_t SceneInfo::map_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.SceneInfo.map_id)
  return _internal_map_id();
}
inline void SceneInfo::_internal_set_map_id(uint32_t value) {
  
  _impl_.map_id_ = value;
}
inline void SceneInfo::set_map_id(uint32_t value) {
  _internal_set_map_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.SceneInfo.map_id)
}

// uint64 owner_uid = 3;
inline void SceneInfo::clear_owner_uid() {
  _impl_.owner_uid_ = uint64_t{0u};
}
inline uint64_t SceneInfo::_internal_owner_uid() const {
  return _impl_.owner_uid_;
}
inline uint64_t SceneInfo::owner_uid() const {
  // @@protoc_insertion_point(field_get:PB.Types.SceneInfo.owner_uid)
  return _internal_owner_uid();
}
inline void SceneInfo::_internal_set_owner_uid(uint64_t value) {
  
  _impl_.owner_uid_ = value;
}
inline void SceneInfo::set_owner_uid(uint64_t value) {
  _internal_set_owner_uid(value);
  // @@protoc_insertion_point(field_set:PB.Types.SceneInfo.owner_uid)
}

// -------------------------------------------------------------------

// BattlePlayerSpec

// uint32 session_id = 1;
inline void BattlePlayerSpec::clear_session_id() {
  _impl_.session_id_ = 0u;
}
inline uint32_t BattlePlayerSpec::_internal_session_id() const {
  return _impl_.session_id_;
}
inline uint32_t BattlePlayerSpec::session_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.BattlePlayerSpec.session_id)
  return _internal_session_id();
}
inline void BattlePlayerSpec::_internal_set_session_id(uint32_t value) {
  
  _impl_.session_id_ = value;
}
inline void BattlePlayerSpec::set_session_id(uint32_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.BattlePlayerSpec.session_id)
}

// int64 player_id = 2;
inline void BattlePlayerSpec::clear_player_id() {
  _impl_.player_id_ = int64_t{0};
}
inline int64_t BattlePlayerSpec::_internal_player_id() const {
  return _impl_.player_id_;
}
inline int64_t BattlePlayerSpec::player_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.BattlePlayerSpec.player_id)
  return _internal_player_id();
}
inline void BattlePlayerSpec::_internal_set_player_id(int64_t value) {
  
  _impl_.player_id_ = value;
}
inline void BattlePlayerSpec::set_player_id(int64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.BattlePlayerSpec.player_id)
}

// int32 class_id = 3;
inline void BattlePlayerSpec::clear_class_id() {
  _impl_.class_id_ = 0;
}
inline int32_t BattlePlayerSpec::_internal_class_id() const {
  return _impl_.class_id_;
}
inline int32_t BattlePlayerSpec::class_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.BattlePlayerSpec.class_id)
  return _internal_class_id();
}
inline void BattlePlayerSpec::_internal_set_class_id(int32_t value) {
  
  _impl_.class_id_ = value;
}
inline void BattlePlayerSpec::set_class_id(int32_t value) {
  _internal_set_class_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.BattlePlayerSpec.class_id)
}

// string name = 4;
inline void BattlePlayerSpec::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& BattlePlayerSpec::name() const {
  // @@protoc_insertion_point(field_get:PB.Types.BattlePlayerSpec.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BattlePlayerSpec::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PB.Types.BattlePlayerSpec.name)
}
inline std::string* BattlePlayerSpec::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:PB.Types.BattlePlayerSpec.name)
  return _s;
}
inline const std::string& BattlePlayerSpec::_internal_name() const {
  return _impl_.name_.Get();
}
inline void BattlePlayerSpec::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* BattlePlayerSpec::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* BattlePlayerSpec::release_name() {
  // @@protoc_insertion_point(field_release:PB.Types.BattlePlayerSpec.name)
  return _impl_.name_.Release();
}
inline void BattlePlayerSpec::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PB.Types.BattlePlayerSpec.name)
}

// int64 character_id = 5;
inline void BattlePlayerSpec::clear_character_id() {
  _impl_.character_id_ = int64_t{0};
}
inline int64_t BattlePlayerSpec::_internal_character_id() const {
  return _impl_.character_id_;
}
inline int64_t BattlePlayerSpec::character_id() const {
  // @@protoc_insertion_point(field_get:PB.Types.BattlePlayerSpec.character_id)
  return _internal_character_id();
}
inline void BattlePlayerSpec::_internal_set_character_id(int64_t value) {
  
  _impl_.character_id_ = value;
}
inline void BattlePlayerSpec::set_character_id(int64_t value) {
  _internal_set_character_id(value);
  // @@protoc_insertion_point(field_set:PB.Types.BattlePlayerSpec.character_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Types
}  // namespace PB

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PB::Types::SceneEnterType> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_game_5ftypes_2eproto
