// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway_client.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_gateway_5fclient_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_gateway_5fclient_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_gateway_5fclient_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_gateway_5fclient_2eproto {
  static const uint32_t offsets[];
};
namespace PB {
namespace GatewayClient {
class GatewayErrorResp;
struct GatewayErrorRespDefaultTypeInternal;
extern GatewayErrorRespDefaultTypeInternal _GatewayErrorResp_default_instance_;
class ServerStatusPush;
struct ServerStatusPushDefaultTypeInternal;
extern ServerStatusPushDefaultTypeInternal _ServerStatusPush_default_instance_;
class ServerStatusReq;
struct ServerStatusReqDefaultTypeInternal;
extern ServerStatusReqDefaultTypeInternal _ServerStatusReq_default_instance_;
class ServiceStatus;
struct ServiceStatusDefaultTypeInternal;
extern ServiceStatusDefaultTypeInternal _ServiceStatus_default_instance_;
}  // namespace GatewayClient
}  // namespace PB
PROTOBUF_NAMESPACE_OPEN
template<> ::PB::GatewayClient::GatewayErrorResp* Arena::CreateMaybeMessage<::PB::GatewayClient::GatewayErrorResp>(Arena*);
template<> ::PB::GatewayClient::ServerStatusPush* Arena::CreateMaybeMessage<::PB::GatewayClient::ServerStatusPush>(Arena*);
template<> ::PB::GatewayClient::ServerStatusReq* Arena::CreateMaybeMessage<::PB::GatewayClient::ServerStatusReq>(Arena*);
template<> ::PB::GatewayClient::ServiceStatus* Arena::CreateMaybeMessage<::PB::GatewayClient::ServiceStatus>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PB {
namespace GatewayClient {

enum ServerStatusReq_MsgId : int {
  ServerStatusReq_MsgId_None = 0,
  ServerStatusReq_MsgId_Id = 1,
  ServerStatusReq_MsgId_ServerStatusReq_MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ServerStatusReq_MsgId_ServerStatusReq_MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ServerStatusReq_MsgId_IsValid(int value);
constexpr ServerStatusReq_MsgId ServerStatusReq_MsgId_MsgId_MIN = ServerStatusReq_MsgId_None;
constexpr ServerStatusReq_MsgId ServerStatusReq_MsgId_MsgId_MAX = ServerStatusReq_MsgId_Id;
constexpr int ServerStatusReq_MsgId_MsgId_ARRAYSIZE = ServerStatusReq_MsgId_MsgId_MAX + 1;

const std::string& ServerStatusReq_MsgId_Name(ServerStatusReq_MsgId value);
template<typename T>
inline const std::string& ServerStatusReq_MsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ServerStatusReq_MsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ServerStatusReq_MsgId_Name.");
  return ServerStatusReq_MsgId_Name(static_cast<ServerStatusReq_MsgId>(enum_t_value));
}
bool ServerStatusReq_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ServerStatusReq_MsgId* value);
enum ServerStatusPush_MsgId : int {
  ServerStatusPush_MsgId_None = 0,
  ServerStatusPush_MsgId_Id = 2,
  ServerStatusPush_MsgId_ServerStatusPush_MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ServerStatusPush_MsgId_ServerStatusPush_MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ServerStatusPush_MsgId_IsValid(int value);
constexpr ServerStatusPush_MsgId ServerStatusPush_MsgId_MsgId_MIN = ServerStatusPush_MsgId_None;
constexpr ServerStatusPush_MsgId ServerStatusPush_MsgId_MsgId_MAX = ServerStatusPush_MsgId_Id;
constexpr int ServerStatusPush_MsgId_MsgId_ARRAYSIZE = ServerStatusPush_MsgId_MsgId_MAX + 1;

const std::string& ServerStatusPush_MsgId_Name(ServerStatusPush_MsgId value);
template<typename T>
inline const std::string& ServerStatusPush_MsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ServerStatusPush_MsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ServerStatusPush_MsgId_Name.");
  return ServerStatusPush_MsgId_Name(static_cast<ServerStatusPush_MsgId>(enum_t_value));
}
bool ServerStatusPush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ServerStatusPush_MsgId* value);
enum GatewayErrorResp_MsgId : int {
  GatewayErrorResp_MsgId_None = 0,
  GatewayErrorResp_MsgId_Id = 3,
  GatewayErrorResp_MsgId_GatewayErrorResp_MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GatewayErrorResp_MsgId_GatewayErrorResp_MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GatewayErrorResp_MsgId_IsValid(int value);
constexpr GatewayErrorResp_MsgId GatewayErrorResp_MsgId_MsgId_MIN = GatewayErrorResp_MsgId_None;
constexpr GatewayErrorResp_MsgId GatewayErrorResp_MsgId_MsgId_MAX = GatewayErrorResp_MsgId_Id;
constexpr int GatewayErrorResp_MsgId_MsgId_ARRAYSIZE = GatewayErrorResp_MsgId_MsgId_MAX + 1;

const std::string& GatewayErrorResp_MsgId_Name(GatewayErrorResp_MsgId value);
template<typename T>
inline const std::string& GatewayErrorResp_MsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GatewayErrorResp_MsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GatewayErrorResp_MsgId_Name.");
  return GatewayErrorResp_MsgId_Name(static_cast<GatewayErrorResp_MsgId>(enum_t_value));
}
bool GatewayErrorResp_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GatewayErrorResp_MsgId* value);
// ===================================================================

class ServerStatusReq final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.GatewayClient.ServerStatusReq) */ {
 public:
  inline ServerStatusReq() : ServerStatusReq(nullptr) {}
  ~ServerStatusReq() override;
  explicit PROTOBUF_CONSTEXPR ServerStatusReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerStatusReq(const ServerStatusReq& from);
  ServerStatusReq(ServerStatusReq&& from) noexcept
    : ServerStatusReq() {
    *this = ::std::move(from);
  }

  inline ServerStatusReq& operator=(const ServerStatusReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerStatusReq& operator=(ServerStatusReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ServerStatusReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerStatusReq* internal_default_instance() {
    return reinterpret_cast<const ServerStatusReq*>(
               &_ServerStatusReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ServerStatusReq& a, ServerStatusReq& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerStatusReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerStatusReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerStatusReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerStatusReq>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ServerStatusReq& from);
  void MergeFrom(const ServerStatusReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ServerStatusReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.GatewayClient.ServerStatusReq";
  }
  protected:
  explicit ServerStatusReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef ServerStatusReq_MsgId MsgId;
  static constexpr MsgId None =
    ServerStatusReq_MsgId_None;
  static constexpr MsgId Id =
    ServerStatusReq_MsgId_Id;
  static inline bool MsgId_IsValid(int value) {
    return ServerStatusReq_MsgId_IsValid(value);
  }
  static constexpr MsgId MsgId_MIN =
    ServerStatusReq_MsgId_MsgId_MIN;
  static constexpr MsgId MsgId_MAX =
    ServerStatusReq_MsgId_MsgId_MAX;
  static constexpr int MsgId_ARRAYSIZE =
    ServerStatusReq_MsgId_MsgId_ARRAYSIZE;
  template<typename T>
  static inline const std::string& MsgId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgId_Name.");
    return ServerStatusReq_MsgId_Name(enum_t_value);
  }
  static inline bool MsgId_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MsgId* value) {
    return ServerStatusReq_MsgId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:PB.GatewayClient.ServerStatusReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gateway_5fclient_2eproto;
};
// -------------------------------------------------------------------

class ServiceStatus final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.GatewayClient.ServiceStatus) */ {
 public:
  inline ServiceStatus() : ServiceStatus(nullptr) {}
  ~ServiceStatus() override;
  explicit PROTOBUF_CONSTEXPR ServiceStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServiceStatus(const ServiceStatus& from);
  ServiceStatus(ServiceStatus&& from) noexcept
    : ServiceStatus() {
    *this = ::std::move(from);
  }

  inline ServiceStatus& operator=(const ServiceStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServiceStatus& operator=(ServiceStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ServiceStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServiceStatus* internal_default_instance() {
    return reinterpret_cast<const ServiceStatus*>(
               &_ServiceStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ServiceStatus& a, ServiceStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(ServiceStatus* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServiceStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServiceStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServiceStatus>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ServiceStatus& from);
  void MergeFrom(const ServiceStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ServiceStatus* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.GatewayClient.ServiceStatus";
  }
  protected:
  explicit ServiceStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceIdFieldNumber = 1,
    kInstanceIdFieldNumber = 2,
    kOnlineFieldNumber = 3,
  };
  // uint32 service_id = 1;
  void clear_service_id();
  uint32_t service_id() const;
  void set_service_id(uint32_t value);
  private:
  uint32_t _internal_service_id() const;
  void _internal_set_service_id(uint32_t value);
  public:

  // uint32 instance_id = 2;
  void clear_instance_id();
  uint32_t instance_id() const;
  void set_instance_id(uint32_t value);
  private:
  uint32_t _internal_instance_id() const;
  void _internal_set_instance_id(uint32_t value);
  public:

  // bool online = 3;
  void clear_online();
  bool online() const;
  void set_online(bool value);
  private:
  bool _internal_online() const;
  void _internal_set_online(bool value);
  public:

  // @@protoc_insertion_point(class_scope:PB.GatewayClient.ServiceStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t service_id_;
    uint32_t instance_id_;
    bool online_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gateway_5fclient_2eproto;
};
// -------------------------------------------------------------------

class ServerStatusPush final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.GatewayClient.ServerStatusPush) */ {
 public:
  inline ServerStatusPush() : ServerStatusPush(nullptr) {}
  ~ServerStatusPush() override;
  explicit PROTOBUF_CONSTEXPR ServerStatusPush(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerStatusPush(const ServerStatusPush& from);
  ServerStatusPush(ServerStatusPush&& from) noexcept
    : ServerStatusPush() {
    *this = ::std::move(from);
  }

  inline ServerStatusPush& operator=(const ServerStatusPush& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerStatusPush& operator=(ServerStatusPush&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ServerStatusPush& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerStatusPush* internal_default_instance() {
    return reinterpret_cast<const ServerStatusPush*>(
               &_ServerStatusPush_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ServerStatusPush& a, ServerStatusPush& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerStatusPush* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerStatusPush* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerStatusPush* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerStatusPush>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ServerStatusPush& from);
  void MergeFrom(const ServerStatusPush& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ServerStatusPush* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.GatewayClient.ServerStatusPush";
  }
  protected:
  explicit ServerStatusPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef ServerStatusPush_MsgId MsgId;
  static constexpr MsgId None =
    ServerStatusPush_MsgId_None;
  static constexpr MsgId Id =
    ServerStatusPush_MsgId_Id;
  static inline bool MsgId_IsValid(int value) {
    return ServerStatusPush_MsgId_IsValid(value);
  }
  static constexpr MsgId MsgId_MIN =
    ServerStatusPush_MsgId_MsgId_MIN;
  static constexpr MsgId MsgId_MAX =
    ServerStatusPush_MsgId_MsgId_MAX;
  static constexpr int MsgId_ARRAYSIZE =
    ServerStatusPush_MsgId_MsgId_ARRAYSIZE;
  template<typename T>
  static inline const std::string& MsgId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgId_Name.");
    return ServerStatusPush_MsgId_Name(enum_t_value);
  }
  static inline bool MsgId_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MsgId* value) {
    return ServerStatusPush_MsgId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kServicesFieldNumber = 1,
  };
  // repeated .PB.GatewayClient.ServiceStatus services = 1;
  int services_size() const;
  private:
  int _internal_services_size() const;
  public:
  void clear_services();
  ::PB::GatewayClient::ServiceStatus* mutable_services(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::GatewayClient::ServiceStatus >*
      mutable_services();
  private:
  const ::PB::GatewayClient::ServiceStatus& _internal_services(int index) const;
  ::PB::GatewayClient::ServiceStatus* _internal_add_services();
  public:
  const ::PB::GatewayClient::ServiceStatus& services(int index) const;
  ::PB::GatewayClient::ServiceStatus* add_services();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::GatewayClient::ServiceStatus >&
      services() const;

  // @@protoc_insertion_point(class_scope:PB.GatewayClient.ServerStatusPush)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::GatewayClient::ServiceStatus > services_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gateway_5fclient_2eproto;
};
// -------------------------------------------------------------------

class GatewayErrorResp final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.GatewayClient.GatewayErrorResp) */ {
 public:
  inline GatewayErrorResp() : GatewayErrorResp(nullptr) {}
  ~GatewayErrorResp() override;
  explicit PROTOBUF_CONSTEXPR GatewayErrorResp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GatewayErrorResp(const GatewayErrorResp& from);
  GatewayErrorResp(GatewayErrorResp&& from) noexcept
    : GatewayErrorResp() {
    *this = ::std::move(from);
  }

  inline GatewayErrorResp& operator=(const GatewayErrorResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline GatewayErrorResp& operator=(GatewayErrorResp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const GatewayErrorResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const GatewayErrorResp* internal_default_instance() {
    return reinterpret_cast<const GatewayErrorResp*>(
               &_GatewayErrorResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GatewayErrorResp& a, GatewayErrorResp& b) {
    a.Swap(&b);
  }
  inline void Swap(GatewayErrorResp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GatewayErrorResp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GatewayErrorResp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GatewayErrorResp>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const GatewayErrorResp& from);
  void MergeFrom(const GatewayErrorResp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GatewayErrorResp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.GatewayClient.GatewayErrorResp";
  }
  protected:
  explicit GatewayErrorResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef GatewayErrorResp_MsgId MsgId;
  static constexpr MsgId None =
    GatewayErrorResp_MsgId_None;
  static constexpr MsgId Id =
    GatewayErrorResp_MsgId_Id;
  static inline bool MsgId_IsValid(int value) {
    return GatewayErrorResp_MsgId_IsValid(value);
  }
  static constexpr MsgId MsgId_MIN =
    GatewayErrorResp_MsgId_MsgId_MIN;
  static constexpr MsgId MsgId_MAX =
    GatewayErrorResp_MsgId_MsgId_MAX;
  static constexpr int MsgId_ARRAYSIZE =
    GatewayErrorResp_MsgId_MsgId_ARRAYSIZE;
  template<typename T>
  static inline const std::string& MsgId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgId_Name.");
    return GatewayErrorResp_MsgId_Name(enum_t_value);
  }
  static inline bool MsgId_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MsgId* value) {
    return GatewayErrorResp_MsgId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // uint32 code = 1;
  void clear_code();
  uint32_t code() const;
  void set_code(uint32_t value);
  private:
  uint32_t _internal_code() const;
  void _internal_set_code(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.GatewayClient.GatewayErrorResp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    uint32_t code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gateway_5fclient_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerStatusReq

// -------------------------------------------------------------------

// ServiceStatus

// uint32 service_id = 1;
inline void ServiceStatus::clear_service_id() {
  _impl_.service_id_ = 0u;
}
inline uint32_t ServiceStatus::_internal_service_id() const {
  return _impl_.service_id_;
}
inline uint32_t ServiceStatus::service_id() const {
  // @@protoc_insertion_point(field_get:PB.GatewayClient.ServiceStatus.service_id)
  return _internal_service_id();
}
inline void ServiceStatus::_internal_set_service_id(uint32_t value) {
  
  _impl_.service_id_ = value;
}
inline void ServiceStatus::set_service_id(uint32_t value) {
  _internal_set_service_id(value);
  // @@protoc_insertion_point(field_set:PB.GatewayClient.ServiceStatus.service_id)
}

// uint32 instance_id = 2;
inline void ServiceStatus::clear_instance_id() {
  _impl_.instance_id_ = 0u;
}
inline uint32_t ServiceStatus::_internal_instance_id() const {
  return _impl_.instance_id_;
}
inline uint32_t ServiceStatus::instance_id() const {
  // @@protoc_insertion_point(field_get:PB.GatewayClient.ServiceStatus.instance_id)
  return _internal_instance_id();
}
inline void ServiceStatus::_internal_set_instance_id(uint32_t value) {
  
  _impl_.instance_id_ = value;
}
inline void ServiceStatus::set_instance_id(uint32_t value) {
  _internal_set_instance_id(value);
  // @@protoc_insertion_point(field_set:PB.GatewayClient.ServiceStatus.instance_id)
}

// bool online = 3;
inline void ServiceStatus::clear_online() {
  _impl_.online_ = false;
}
inline bool ServiceStatus::_internal_online() const {
  return _impl_.online_;
}
inline bool ServiceStatus::online() const {
  // @@protoc_insertion_point(field_get:PB.GatewayClient.ServiceStatus.online)
  return _internal_online();
}
inline void ServiceStatus::_internal_set_online(bool value) {
  
  _impl_.online_ = value;
}
inline void ServiceStatus::set_online(bool value) {
  _internal_set_online(value);
  // @@protoc_insertion_point(field_set:PB.GatewayClient.ServiceStatus.online)
}

// -------------------------------------------------------------------

// ServerStatusPush

// repeated .PB.GatewayClient.ServiceStatus services = 1;
inline int ServerStatusPush::_internal_services_size() const {
  return _impl_.services_.size();
}
inline int ServerStatusPush::services_size() const {
  return _internal_services_size();
}
inline void ServerStatusPush::clear_services() {
  _impl_.services_.Clear();
}
inline ::PB::GatewayClient::ServiceStatus* ServerStatusPush::mutable_services(int index) {
  // @@protoc_insertion_point(field_mutable:PB.GatewayClient.ServerStatusPush.services)
  return _impl_.services_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::GatewayClient::ServiceStatus >*
ServerStatusPush::mutable_services() {
  // @@protoc_insertion_point(field_mutable_list:PB.GatewayClient.ServerStatusPush.services)
  return &_impl_.services_;
}
inline const ::PB::GatewayClient::ServiceStatus& ServerStatusPush::_internal_services(int index) const {
  return _impl_.services_.Get(index);
}
inline const ::PB::GatewayClient::ServiceStatus& ServerStatusPush::services(int index) const {
  // @@protoc_insertion_point(field_get:PB.GatewayClient.ServerStatusPush.services)
  return _internal_services(index);
}
inline ::PB::GatewayClient::ServiceStatus* ServerStatusPush::_internal_add_services() {
  return _impl_.services_.Add();
}
inline ::PB::GatewayClient::ServiceStatus* ServerStatusPush::add_services() {
  ::PB::GatewayClient::ServiceStatus* _add = _internal_add_services();
  // @@protoc_insertion_point(field_add:PB.GatewayClient.ServerStatusPush.services)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::GatewayClient::ServiceStatus >&
ServerStatusPush::services() const {
  // @@protoc_insertion_point(field_list:PB.GatewayClient.ServerStatusPush.services)
  return _impl_.services_;
}

// -------------------------------------------------------------------

// GatewayErrorResp

// uint32 code = 1;
inline void GatewayErrorResp::clear_code() {
  _impl_.code_ = 0u;
}
inline uint32_t GatewayErrorResp::_internal_code() const {
  return _impl_.code_;
}
inline uint32_t GatewayErrorResp::code() const {
  // @@protoc_insertion_point(field_get:PB.GatewayClient.GatewayErrorResp.code)
  return _internal_code();
}
inline void GatewayErrorResp::_internal_set_code(uint32_t value) {
  
  _impl_.code_ = value;
}
inline void GatewayErrorResp::set_code(uint32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:PB.GatewayClient.GatewayErrorResp.code)
}

// string message = 2;
inline void GatewayErrorResp::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& GatewayErrorResp::message() const {
  // @@protoc_insertion_point(field_get:PB.GatewayClient.GatewayErrorResp.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GatewayErrorResp::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PB.GatewayClient.GatewayErrorResp.message)
}
inline std::string* GatewayErrorResp::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:PB.GatewayClient.GatewayErrorResp.message)
  return _s;
}
inline const std::string& GatewayErrorResp::_internal_message() const {
  return _impl_.message_.Get();
}
inline void GatewayErrorResp::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* GatewayErrorResp::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* GatewayErrorResp::release_message() {
  // @@protoc_insertion_point(field_release:PB.GatewayClient.GatewayErrorResp.message)
  return _impl_.message_.Release();
}
inline void GatewayErrorResp::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PB.GatewayClient.GatewayErrorResp.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace GatewayClient
}  // namespace PB

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PB::GatewayClient::ServerStatusReq_MsgId> : ::std::true_type {};
template <> struct is_proto_enum< ::PB::GatewayClient::ServerStatusPush_MsgId> : ::std::true_type {};
template <> struct is_proto_enum< ::PB::GatewayClient::GatewayErrorResp_MsgId> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_gateway_5fclient_2eproto
