// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway_client.proto

#include "gateway_client.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace PB {
namespace GatewayClient {
PROTOBUF_CONSTEXPR ServerStatusReq::ServerStatusReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._cached_size_)*/{}} {}
struct ServerStatusReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServerStatusReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServerStatusReqDefaultTypeInternal() {}
  union {
    ServerStatusReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServerStatusReqDefaultTypeInternal _ServerStatusReq_default_instance_;
PROTOBUF_CONSTEXPR ServiceStatus::ServiceStatus(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.service_id_)*/0u
  , /*decltype(_impl_.instance_id_)*/0u
  , /*decltype(_impl_.online_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ServiceStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServiceStatusDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServiceStatusDefaultTypeInternal() {}
  union {
    ServiceStatus _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServiceStatusDefaultTypeInternal _ServiceStatus_default_instance_;
PROTOBUF_CONSTEXPR ServerStatusPush::ServerStatusPush(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.services_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ServerStatusPushDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServerStatusPushDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServerStatusPushDefaultTypeInternal() {}
  union {
    ServerStatusPush _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServerStatusPushDefaultTypeInternal _ServerStatusPush_default_instance_;
PROTOBUF_CONSTEXPR GatewayErrorResp::GatewayErrorResp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.code_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GatewayErrorRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GatewayErrorRespDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GatewayErrorRespDefaultTypeInternal() {}
  union {
    GatewayErrorResp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GatewayErrorRespDefaultTypeInternal _GatewayErrorResp_default_instance_;
}  // namespace GatewayClient
}  // namespace PB
namespace PB {
namespace GatewayClient {
bool ServerStatusReq_MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> ServerStatusReq_MsgId_strings[2] = {};

static const char ServerStatusReq_MsgId_names[] =
  "Id"
  "None";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry ServerStatusReq_MsgId_entries[] = {
  { {ServerStatusReq_MsgId_names + 0, 2}, 1 },
  { {ServerStatusReq_MsgId_names + 2, 4}, 0 },
};

static const int ServerStatusReq_MsgId_entries_by_number[] = {
  1, // 0 -> None
  0, // 1 -> Id
};

const std::string& ServerStatusReq_MsgId_Name(
    ServerStatusReq_MsgId value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          ServerStatusReq_MsgId_entries,
          ServerStatusReq_MsgId_entries_by_number,
          2, ServerStatusReq_MsgId_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      ServerStatusReq_MsgId_entries,
      ServerStatusReq_MsgId_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     ServerStatusReq_MsgId_strings[idx].get();
}
bool ServerStatusReq_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ServerStatusReq_MsgId* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      ServerStatusReq_MsgId_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<ServerStatusReq_MsgId>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr ServerStatusReq_MsgId ServerStatusReq::None;
constexpr ServerStatusReq_MsgId ServerStatusReq::Id;
constexpr ServerStatusReq_MsgId ServerStatusReq::MsgId_MIN;
constexpr ServerStatusReq_MsgId ServerStatusReq::MsgId_MAX;
constexpr int ServerStatusReq::MsgId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
bool ServerStatusPush_MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> ServerStatusPush_MsgId_strings[2] = {};

static const char ServerStatusPush_MsgId_names[] =
  "Id"
  "None";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry ServerStatusPush_MsgId_entries[] = {
  { {ServerStatusPush_MsgId_names + 0, 2}, 2 },
  { {ServerStatusPush_MsgId_names + 2, 4}, 0 },
};

static const int ServerStatusPush_MsgId_entries_by_number[] = {
  1, // 0 -> None
  0, // 2 -> Id
};

const std::string& ServerStatusPush_MsgId_Name(
    ServerStatusPush_MsgId value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          ServerStatusPush_MsgId_entries,
          ServerStatusPush_MsgId_entries_by_number,
          2, ServerStatusPush_MsgId_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      ServerStatusPush_MsgId_entries,
      ServerStatusPush_MsgId_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     ServerStatusPush_MsgId_strings[idx].get();
}
bool ServerStatusPush_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ServerStatusPush_MsgId* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      ServerStatusPush_MsgId_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<ServerStatusPush_MsgId>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr ServerStatusPush_MsgId ServerStatusPush::None;
constexpr ServerStatusPush_MsgId ServerStatusPush::Id;
constexpr ServerStatusPush_MsgId ServerStatusPush::MsgId_MIN;
constexpr ServerStatusPush_MsgId ServerStatusPush::MsgId_MAX;
constexpr int ServerStatusPush::MsgId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
bool GatewayErrorResp_MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 3:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> GatewayErrorResp_MsgId_strings[2] = {};

static const char GatewayErrorResp_MsgId_names[] =
  "Id"
  "None";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry GatewayErrorResp_MsgId_entries[] = {
  { {GatewayErrorResp_MsgId_names + 0, 2}, 3 },
  { {GatewayErrorResp_MsgId_names + 2, 4}, 0 },
};

static const int GatewayErrorResp_MsgId_entries_by_number[] = {
  1, // 0 -> None
  0, // 3 -> Id
};

const std::string& GatewayErrorResp_MsgId_Name(
    GatewayErrorResp_MsgId value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          GatewayErrorResp_MsgId_entries,
          GatewayErrorResp_MsgId_entries_by_number,
          2, GatewayErrorResp_MsgId_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      GatewayErrorResp_MsgId_entries,
      GatewayErrorResp_MsgId_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     GatewayErrorResp_MsgId_strings[idx].get();
}
bool GatewayErrorResp_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GatewayErrorResp_MsgId* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      GatewayErrorResp_MsgId_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<GatewayErrorResp_MsgId>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr GatewayErrorResp_MsgId GatewayErrorResp::None;
constexpr GatewayErrorResp_MsgId GatewayErrorResp::Id;
constexpr GatewayErrorResp_MsgId GatewayErrorResp::MsgId_MIN;
constexpr GatewayErrorResp_MsgId GatewayErrorResp::MsgId_MAX;
constexpr int GatewayErrorResp::MsgId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class ServerStatusReq::_Internal {
 public:
};

ServerStatusReq::ServerStatusReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.GatewayClient.ServerStatusReq)
}
ServerStatusReq::ServerStatusReq(const ServerStatusReq& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  ServerStatusReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:PB.GatewayClient.ServerStatusReq)
}

inline void ServerStatusReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}
  };
}

ServerStatusReq::~ServerStatusReq() {
  // @@protoc_insertion_point(destructor:PB.GatewayClient.ServerStatusReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ServerStatusReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ServerStatusReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ServerStatusReq::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.GatewayClient.ServerStatusReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<std::string>();
}

const char* ServerStatusReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ServerStatusReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.GatewayClient.ServerStatusReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.GatewayClient.ServerStatusReq)
  return target;
}

size_t ServerStatusReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.GatewayClient.ServerStatusReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ServerStatusReq::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const ServerStatusReq*>(
      &from));
}

void ServerStatusReq::MergeFrom(const ServerStatusReq& from) {
  ServerStatusReq* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.GatewayClient.ServerStatusReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void ServerStatusReq::CopyFrom(const ServerStatusReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.GatewayClient.ServerStatusReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerStatusReq::IsInitialized() const {
  return true;
}

void ServerStatusReq::InternalSwap(ServerStatusReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
}

std::string ServerStatusReq::GetTypeName() const {
  return "PB.GatewayClient.ServerStatusReq";
}


// ===================================================================

class ServiceStatus::_Internal {
 public:
};

ServiceStatus::ServiceStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.GatewayClient.ServiceStatus)
}
ServiceStatus::ServiceStatus(const ServiceStatus& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  ServiceStatus* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.service_id_){}
    , decltype(_impl_.instance_id_){}
    , decltype(_impl_.online_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&_impl_.service_id_, &from._impl_.service_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.online_) -
    reinterpret_cast<char*>(&_impl_.service_id_)) + sizeof(_impl_.online_));
  // @@protoc_insertion_point(copy_constructor:PB.GatewayClient.ServiceStatus)
}

inline void ServiceStatus::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.service_id_){0u}
    , decltype(_impl_.instance_id_){0u}
    , decltype(_impl_.online_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ServiceStatus::~ServiceStatus() {
  // @@protoc_insertion_point(destructor:PB.GatewayClient.ServiceStatus)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ServiceStatus::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ServiceStatus::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ServiceStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.GatewayClient.ServiceStatus)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.service_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.online_) -
      reinterpret_cast<char*>(&_impl_.service_id_)) + sizeof(_impl_.online_));
  _internal_metadata_.Clear<std::string>();
}

const char* ServiceStatus::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 service_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.service_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 instance_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool online = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.online_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ServiceStatus::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.GatewayClient.ServiceStatus)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 service_id = 1;
  if (this->_internal_service_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_service_id(), target);
  }

  // uint32 instance_id = 2;
  if (this->_internal_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_instance_id(), target);
  }

  // bool online = 3;
  if (this->_internal_online() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_online(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.GatewayClient.ServiceStatus)
  return target;
}

size_t ServiceStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.GatewayClient.ServiceStatus)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 service_id = 1;
  if (this->_internal_service_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_service_id());
  }

  // uint32 instance_id = 2;
  if (this->_internal_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_instance_id());
  }

  // bool online = 3;
  if (this->_internal_online() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ServiceStatus::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const ServiceStatus*>(
      &from));
}

void ServiceStatus::MergeFrom(const ServiceStatus& from) {
  ServiceStatus* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.GatewayClient.ServiceStatus)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_service_id() != 0) {
    _this->_internal_set_service_id(from._internal_service_id());
  }
  if (from._internal_instance_id() != 0) {
    _this->_internal_set_instance_id(from._internal_instance_id());
  }
  if (from._internal_online() != 0) {
    _this->_internal_set_online(from._internal_online());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void ServiceStatus::CopyFrom(const ServiceStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.GatewayClient.ServiceStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServiceStatus::IsInitialized() const {
  return true;
}

void ServiceStatus::InternalSwap(ServiceStatus* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ServiceStatus, _impl_.online_)
      + sizeof(ServiceStatus::_impl_.online_)
      - PROTOBUF_FIELD_OFFSET(ServiceStatus, _impl_.service_id_)>(
          reinterpret_cast<char*>(&_impl_.service_id_),
          reinterpret_cast<char*>(&other->_impl_.service_id_));
}

std::string ServiceStatus::GetTypeName() const {
  return "PB.GatewayClient.ServiceStatus";
}


// ===================================================================

class ServerStatusPush::_Internal {
 public:
};

ServerStatusPush::ServerStatusPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.GatewayClient.ServerStatusPush)
}
ServerStatusPush::ServerStatusPush(const ServerStatusPush& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  ServerStatusPush* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.services_){from._impl_.services_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:PB.GatewayClient.ServerStatusPush)
}

inline void ServerStatusPush::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.services_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ServerStatusPush::~ServerStatusPush() {
  // @@protoc_insertion_point(destructor:PB.GatewayClient.ServerStatusPush)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ServerStatusPush::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.services_.~RepeatedPtrField();
}

void ServerStatusPush::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ServerStatusPush::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.GatewayClient.ServerStatusPush)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.services_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* ServerStatusPush::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .PB.GatewayClient.ServiceStatus services = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_services(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ServerStatusPush::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.GatewayClient.ServerStatusPush)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .PB.GatewayClient.ServiceStatus services = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_services_size()); i < n; i++) {
    const auto& repfield = this->_internal_services(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.GatewayClient.ServerStatusPush)
  return target;
}

size_t ServerStatusPush::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.GatewayClient.ServerStatusPush)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .PB.GatewayClient.ServiceStatus services = 1;
  total_size += 1UL * this->_internal_services_size();
  for (const auto& msg : this->_impl_.services_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ServerStatusPush::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const ServerStatusPush*>(
      &from));
}

void ServerStatusPush::MergeFrom(const ServerStatusPush& from) {
  ServerStatusPush* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.GatewayClient.ServerStatusPush)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.services_.MergeFrom(from._impl_.services_);
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void ServerStatusPush::CopyFrom(const ServerStatusPush& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.GatewayClient.ServerStatusPush)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerStatusPush::IsInitialized() const {
  return true;
}

void ServerStatusPush::InternalSwap(ServerStatusPush* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.services_.InternalSwap(&other->_impl_.services_);
}

std::string ServerStatusPush::GetTypeName() const {
  return "PB.GatewayClient.ServerStatusPush";
}


// ===================================================================

class GatewayErrorResp::_Internal {
 public:
};

GatewayErrorResp::GatewayErrorResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.GatewayClient.GatewayErrorResp)
}
GatewayErrorResp::GatewayErrorResp(const GatewayErrorResp& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  GatewayErrorResp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.code_ = from._impl_.code_;
  // @@protoc_insertion_point(copy_constructor:PB.GatewayClient.GatewayErrorResp)
}

inline void GatewayErrorResp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GatewayErrorResp::~GatewayErrorResp() {
  // @@protoc_insertion_point(destructor:PB.GatewayClient.GatewayErrorResp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GatewayErrorResp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void GatewayErrorResp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GatewayErrorResp::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.GatewayClient.GatewayErrorResp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.code_ = 0u;
  _internal_metadata_.Clear<std::string>();
}

const char* GatewayErrorResp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GatewayErrorResp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.GatewayClient.GatewayErrorResp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_code(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PB.GatewayClient.GatewayErrorResp.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.GatewayClient.GatewayErrorResp)
  return target;
}

size_t GatewayErrorResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.GatewayClient.GatewayErrorResp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // uint32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_code());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GatewayErrorResp::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const GatewayErrorResp*>(
      &from));
}

void GatewayErrorResp::MergeFrom(const GatewayErrorResp& from) {
  GatewayErrorResp* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.GatewayClient.GatewayErrorResp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void GatewayErrorResp::CopyFrom(const GatewayErrorResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.GatewayClient.GatewayErrorResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GatewayErrorResp::IsInitialized() const {
  return true;
}

void GatewayErrorResp::InternalSwap(GatewayErrorResp* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.code_, other->_impl_.code_);
}

std::string GatewayErrorResp::GetTypeName() const {
  return "PB.GatewayClient.GatewayErrorResp";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace GatewayClient
}  // namespace PB
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PB::GatewayClient::ServerStatusReq*
Arena::CreateMaybeMessage< ::PB::GatewayClient::ServerStatusReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::GatewayClient::ServerStatusReq >(arena);
}
template<> PROTOBUF_NOINLINE ::PB::GatewayClient::ServiceStatus*
Arena::CreateMaybeMessage< ::PB::GatewayClient::ServiceStatus >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::GatewayClient::ServiceStatus >(arena);
}
template<> PROTOBUF_NOINLINE ::PB::GatewayClient::ServerStatusPush*
Arena::CreateMaybeMessage< ::PB::GatewayClient::ServerStatusPush >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::GatewayClient::ServerStatusPush >(arena);
}
template<> PROTOBUF_NOINLINE ::PB::GatewayClient::GatewayErrorResp*
Arena::CreateMaybeMessage< ::PB::GatewayClient::GatewayErrorResp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::GatewayClient::GatewayErrorResp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
