#include "ui/UiConfig.h"

namespace gameui
{

const RoleIntro kRoleIntros[mugen::CharacterClass::kCount] = {
    {
        {
            {"神月",
             2,
             "使用长剑为武器，可以操控温度极高的蓝色火焰，擅长进行近战冲锋和爆发。",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_shenyue",
             {10012, 1.0f, 1.0f, -60.0f, 20.0f, "0"},
             "video/video_player/ui_zhiyejieshao_shenyue.mp4"},
            {"苍炎骑士",
             4,
             "火力全开的蓝焰剑士，将高温的火焰具形化，火焰护体，龙焰之盾，成为战场上的防御核心",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_cangyanqishi",
             {10308, 1.1f, 1.1f, 50.0f, -85.0f, "0"},
             "video/video_player/ui_zhiyejieshao_cangyanqishi.mp4"},
            {"次元领主",
             3,
             "掌握时空的双刃剑士，额外使用次元之刃，斩破时空，穿梭次元，是为战场上的的绝对王牌",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_ciyuanlingzhu",
             {10309, 1.0f, 1.0f, 20.0f, -40.0f, "0"},
             "video/video_player/ui_zhiyejieshao_ciyuanlingzhu.mp4"},
        },
        "ui://CharacterLobby/ui_juesechuangjian_juexingfangxiang_jindutiao_shuxing",
    },
    {
        {
            {"LING",
             3,
             "使用刺刃为武器，可以进行能量具现的暗器攻击，擅长隐身刺杀和造物穿刺。",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_ling",
             {10063, 1.0f, 1.0f, -20.0f, 25.0f, "0"},
             "video/video_player/ui_zhiyejieshao_ling.mp4"},
            {"逐影之心",
             5,
             "恪守使命的致命兵器，领悟影的含义，流血中毒，减速禁锢，化身折磨对手的暗影毒刺",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_zhuyingzhixin",
             {10310, 1.0f, 1.0f, 50.0f, 0.0f, "0"},
             "video/video_player/ui_zhiyejieshao_zhuyingzhixin.mp4"},
            {"神兵之眼",
             2,
             "火力全开的最终堡垒，增强具现化的异能，圣矛穿刺，飞刃旋舞，成为横扫千军的毁灭重炮",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_shenbingzhiyan",
             {10311, 1.0f, 1.0f, 20.0f, 0.0f, "0"},
             "video/video_player/ui_zhiyejieshao_shenbingzhiyan.mp4"},
        },
        "ui://CharacterLobby/ui_juesechuangjian_juexingfangxiang_jindutiao_shuxing_02",
    },
    {
        {
            {"未开放",
             3,
             "使用刺刃为武器，可以进行能量具现的暗器攻击，擅长隐身刺杀和造物穿刺。",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_ling",
             {10063, 1.0f, 1.0f, -20.0f, 25.0f, "0"},
             "video/video_player/ui_zhiyejieshao_ling.mp4"},
            {"逐影之心",
             5,
             "恪守使命的致命兵器，领悟影的含义，流血中毒，减速禁锢，化身折磨对手的暗影毒刺",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_zhuyingzhixin",
             {10310, 1.0f, 1.0f, 50.0f, 0.0f, "0"},
             "video/video_player/ui_zhiyejieshao_zhuyingzhixin.mp4"},
            {"神兵之眼",
             2,
             "火力全开的最终堡垒，增强具现化的异能，圣矛穿刺，飞刃旋舞，成为横扫千军的毁灭重炮",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_shenbingzhiyan",
             {10311, 1.0f, 1.0f, 20.0f, 0.0f, "0"},
             "video/video_player/ui_zhiyejieshao_shenbingzhiyan.mp4"},
        },
        "ui://CharacterLobby/ui_juesechuangjian_juexingfangxiang_jindutiao_shuxing_02",
    },
    {
        {
            {"莉莉姆",
             1,
             "使用魔杖为武器，可以进行召唤虚空，雷光之力的异能攻击，擅长能量控制与大范围魔法",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_lilimu",
             {10360, 1.0f, 1.0f, -20.0f, -475.0f, "0"},
             "video/video_player/ui_zhiyejieshao_lilimu.mp4"},
            {"虚空魔女",
             4,
             "掌控暗黑虚空能量的术士，召唤怨灵与魔兽攻击敌人，是敌人眼中最恐怖的存在",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_xukongmonv",
             {10361, 1.0f, 1.0f, 30.0f, -400.0f, "0"},
             "video/video_player/ui_zhiyejieshao_xukongmonv.mp4"},
            {"雷光神使",
             1,
             "驱使雷电的元素使者，以雷光之力惩戒对手，召唤雷电精灵，伴随身边作战",
             "ui://CharacterLobby/ui_juesechuangjian_zhujiemian_mingzi_leiguangshenshi",
             {10362, 1.0f, 1.0f, 7.0f, -350.0f, "0"},
             "video/video_player/ui_zhiyejieshao_leiguangshenshi.mp4"},
        },
        "ui://CharacterLobby/ui_juesechuangjian_juexingfangxiang_jindutiao_shuxing_03",
    },
};

const LookSet kLookIcons[mugen::CharacterClass::kCount] = {
    {
        {"ui://CharacterLobby/ui_juesechuangjian_tou_01_1", "ui://CharacterLobby/ui_juesechuangjian_tou_01_2",
         "ui://CharacterLobby/ui_juesechuangjian_tou_01_3", "ui://CharacterLobby/ui_juesechuangjian_tou_01_4",
         "ui://CharacterLobby/ui_juesechuangjian_tou_01_5"},
        {101004, 101044, 101054, 101064, 101074},
        {"ui://CharacterLobby/ui_juesechuangjian_shizhuang_01_1",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_01_2",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_01_3",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_01_4",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_01_5"},
        {101002, 101042, 101052, 101062, 101072},
        {101007, 101047, 101057, 101067, 101077},
    },
    {
        {"ui://CharacterLobby/ui_juesechuangjian_tou_03_1", "ui://CharacterLobby/ui_juesechuangjian_tou_03_2",
         "ui://CharacterLobby/ui_juesechuangjian_tou_03_3", "ui://CharacterLobby/ui_juesechuangjian_tou_03_4",
         "ui://CharacterLobby/ui_juesechuangjian_tou_03_5"},
        {102004, 102044, 102054, 102064, 102074},
        {"ui://CharacterLobby/ui_juesechuangjian_shizhuang_03_1",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_03_2",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_03_3",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_03_4",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_03_5"},
        {102002, 102042, 102052, 102062, 102072},
        {102007, 102047, 102057, 102067, 102077},
    },
    {
        {"ui://CharacterLobby/ui_juesechuangjian_tou_02_1", "ui://CharacterLobby/ui_juesechuangjian_tou_02_2",
         "ui://CharacterLobby/ui_juesechuangjian_tou_02_3", "ui://CharacterLobby/ui_juesechuangjian_tou_02_4",
         "ui://CharacterLobby/ui_juesechuangjian_tou_02_5"},
        {103004, 103044, 103054, 103064, 103074},
        {"ui://CharacterLobby/ui_juesechuangjian_shizhuang_02_1",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_02_2",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_02_3",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_02_4",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_02_5"},
        {103002, 103042, 103052, 103062, 103072},
        {103007, 103047, 103057, 103067, 103077},
    },
    {
        {"ui://CharacterLobby/ui_juesechuangjian_tou_04_1", "ui://CharacterLobby/ui_juesechuangjian_tou_04_2",
         "ui://CharacterLobby/ui_juesechuangjian_tou_04_3", "ui://CharacterLobby/ui_juesechuangjian_tou_04_4",
         "ui://CharacterLobby/ui_juesechuangjian_tou_04_5"},
        {104004, 104044, 104054, 104064, 104074},
        {"ui://CharacterLobby/ui_juesechuangjian_shizhuang_04_1",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_04_2",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_04_3",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_04_4",
         "ui://CharacterLobby/ui_juesechuangjian_shizhuang_04_5"},
        {104002, 104042, 104052, 104062, 104072},
        {104007, 104047, 104057, 104067, 104077},
    },
};

}  // namespace gameui
